# Generated by Django 5.1.5 on 2026-08-12 09:26

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Django admin access. Reserved for platform operators — the HRMS itself is administered through the API, not Django admin.')),
                ('must_change_password', models.BooleanField(default=False, help_text='Set when HR provisions an account with a temporary password.')),
                ('failed_login_count', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('mfa_secret', models.CharField(blank=True, max_length=64, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['email'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('layer', models.PositiveSmallIntegerField(choices=[(1, 'Layer 1 — Leadership'), (2, 'Layer 2 — Department Head'), (3, 'Layer 3 — Manager'), (4, 'Layer 4 — Executive'), (5, 'Layer 5 — Staff')], db_index=True)),
                ('is_read_only', models.BooleanField(default=False, help_text='Principal may never mutate anything. Applied as a clamp AFTER the permission matrix and any per-user override, so no data change can grant a write. Also blocked at the middleware layer.')),
                ('can_manage_users', models.BooleanField(default=False, help_text='Prerequisite for any USER or ROLE permission. Without it, those resources are stripped from the resolved grants regardless of what the matrix says.')),
                ('requires_employee', models.BooleanField(default=True, help_text='If set, a holder with no linked Employee resolves to no access at all. False only for org-level roles (admin, ceo) which must work before any Employee records exist.')),
                ('is_grantable', models.BooleanField(default=True, help_text='False means the role can only be assigned by bootstrap (admin).')),
                ('is_system', models.BooleanField(default=True, help_text='Seeded canonical role. code/layer/flags are immutable.')),
                ('department_kind', models.CharField(blank=True, choices=[('medical', 'Medical'), ('operations', 'Operations'), ('hr', 'Human Resources'), ('finance', 'Accounts & Finance'), ('other', 'Other')], max_length=20)),
                ('dashboard_key', models.CharField(choices=[('ceo', 'CEO — organization-wide, read-only'), ('admin', 'Admin — full system management'), ('department', 'Department head'), ('manager', 'Manager'), ('executive', 'Executive'), ('self', 'Self-service')], default='self', max_length=40)),
                ('max_seats', models.PositiveSmallIntegerField(blank=True, help_text='Cap on active grants. NULL = unlimited.', null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['layer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('resource', models.CharField(choices=[('user', 'User accounts'), ('role', 'Roles and permissions'), ('department', 'Departments'), ('designation', 'Designations'), ('location', 'Locations'), ('org_settings', 'Organization settings'), ('employee', 'Employee records'), ('employee_document', 'Employee documents'), ('probation_review', 'Probation reviews'), ('asset', 'Assets'), ('asset_allocation', 'Asset allocations'), ('email_account', 'Company email accounts'), ('job_opening', 'Job openings'), ('candidate', 'Candidates'), ('application', 'Applications'), ('interview', 'Interviews'), ('interview_feedback', 'Interview feedback'), ('department_decision', 'Department hiring decisions'), ('offer', 'Offers'), ('hiring_workflow', 'Hiring workflow configuration'), ('onboarding', 'Onboarding'), ('offboarding', 'Offboarding'), ('letter', 'Employee letters'), ('attendance', 'Attendance'), ('regularization', 'Attendance regularization'), ('leave_request', 'Leave requests'), ('leave_policy', 'Leave policy configuration'), ('salary', 'Salary structures'), ('payroll_run', 'Payroll runs'), ('payslip', 'Payslips'), ('payroll_adjustment', 'Payroll adjustments'), ('statutory_config', 'Statutory configuration'), ('policy_doc', 'Policy documents'), ('audit_log', 'Audit log'), ('notification', 'Notifications'), ('report', 'Reports'), ('dashboard_org', 'Organization-wide dashboard'), ('dashboard_department', 'Department dashboard'), ('dashboard_team', 'Team dashboard')], db_index=True, max_length=40)),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('approve', 'Approve'), ('export', 'Export'), ('reject', 'Reject'), ('override', 'Override decision'), ('recommend', 'Recommend decision'), ('decide', 'Decide')], max_length=20)),
                ('scope', models.PositiveSmallIntegerField(choices=[(0, 'No access'), (1, 'Own records only'), (2, 'Own reporting tree'), (3, 'Own department and its sub-departments'), (4, 'Whole organization')], default=0)),
                ('is_customized', models.BooleanField(default=False, help_text='Set when an administrator edits this cell. The seeder then leaves it alone, so re-running seed_roles never silently reverts a deliberate change.')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.role')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role__layer', 'resource', 'action'],
            },
        ),
        migrations.CreateModel(
            name='UserPermissionOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('resource', models.CharField(choices=[('user', 'User accounts'), ('role', 'Roles and permissions'), ('department', 'Departments'), ('designation', 'Designations'), ('location', 'Locations'), ('org_settings', 'Organization settings'), ('employee', 'Employee records'), ('employee_document', 'Employee documents'), ('probation_review', 'Probation reviews'), ('asset', 'Assets'), ('asset_allocation', 'Asset allocations'), ('email_account', 'Company email accounts'), ('job_opening', 'Job openings'), ('candidate', 'Candidates'), ('application', 'Applications'), ('interview', 'Interviews'), ('interview_feedback', 'Interview feedback'), ('department_decision', 'Department hiring decisions'), ('offer', 'Offers'), ('hiring_workflow', 'Hiring workflow configuration'), ('onboarding', 'Onboarding'), ('offboarding', 'Offboarding'), ('letter', 'Employee letters'), ('attendance', 'Attendance'), ('regularization', 'Attendance regularization'), ('leave_request', 'Leave requests'), ('leave_policy', 'Leave policy configuration'), ('salary', 'Salary structures'), ('payroll_run', 'Payroll runs'), ('payslip', 'Payslips'), ('payroll_adjustment', 'Payroll adjustments'), ('statutory_config', 'Statutory configuration'), ('policy_doc', 'Policy documents'), ('audit_log', 'Audit log'), ('notification', 'Notifications'), ('report', 'Reports'), ('dashboard_org', 'Organization-wide dashboard'), ('dashboard_department', 'Department dashboard'), ('dashboard_team', 'Team dashboard')], max_length=40)),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('approve', 'Approve'), ('export', 'Export'), ('reject', 'Reject'), ('override', 'Override decision'), ('recommend', 'Recommend decision'), ('decide', 'Decide')], max_length=20)),
                ('scope', models.PositiveSmallIntegerField(choices=[(0, 'No access'), (1, 'Own records only'), (2, 'Own reporting tree'), (3, 'Own department and its sub-departments'), (4, 'Whole organization')])),
                ('reason', models.CharField(help_text='Why this exception exists. Required — an unexplained permission grant is impossible to review later.', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, help_text='NULL = permanent. Prefer an expiry.', null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__email', 'resource', 'action'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='accounts.role')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__email', 'role__layer'],
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['layer', 'is_active'], name='accounts_ro_layer_0ca962_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.CheckConstraint(condition=models.Q(('can_manage_users', True), ('is_read_only', True), _negated=True), name='ck_role_readonly_cannot_manage_users'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'resource'], name='accounts_ro_role_id_d13d58_idx'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'resource', 'action'), name='uniq_roleperm_role_res_act'),
        ),
        migrations.AddIndex(
            model_name='userpermissionoverride',
            index=models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_89c917_idx'),
        ),
        migrations.AddConstraint(
            model_name='userpermissionoverride',
            constraint=models.UniqueConstraint(fields=('user', 'resource', 'action'), name='uniq_override_user_res_act'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_2517ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='uniq_userrole_user_role'),
        ),
    ]
