# Generated by Django 5.1.5 on 2026-08-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('approve', 'Approve'), ('export', 'Export'), ('reject', 'Reject'), ('override', 'Override decision'), ('recommend', 'Recommend decision'), ('decide', 'Decide'), ('import', 'Bulk import')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userpermissionoverride',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('approve', 'Approve'), ('export', 'Export'), ('reject', 'Reject'), ('override', 'Override decision'), ('recommend', 'Recommend decision'), ('decide', 'Decide'), ('import', 'Bulk import')], max_length=20),
        ),
    ]
