# Generated by Django 5.1.5 on 2026-09-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_role_org_name'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_role_org_code'),
        ),
    ]
