# Generated by Django 5.1.5 on 2026-08-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_import_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='resource',
            field=models.CharField(choices=[('user', 'User accounts'), ('role', 'Roles and permissions'), ('department', 'Departments'), ('designation', 'Designations'), ('location', 'Locations'), ('org_settings', 'Organization settings'), ('employee', 'Employee records'), ('employee_document', 'Employee documents'), ('probation_review', 'Probation reviews'), ('asset', 'Assets'), ('asset_allocation', 'Asset allocations'), ('email_account', 'Company email accounts'), ('job_opening', 'Job openings'), ('candidate', 'Candidates'), ('application', 'Applications'), ('interview', 'Interviews'), ('interview_feedback', 'Interview feedback'), ('department_decision', 'Department hiring decisions'), ('offer', 'Offers'), ('hiring_workflow', 'Hiring workflow configuration'), ('onboarding', 'Onboarding'), ('offboarding', 'Offboarding'), ('letter', 'Employee letters'), ('attendance', 'Attendance'), ('regularization', 'Attendance regularization'), ('attendance_device', 'Biometric attendance devices'), ('leave_request', 'Leave requests'), ('leave_policy', 'Leave policy configuration'), ('salary', 'Salary structures'), ('payroll_run', 'Payroll runs'), ('payslip', 'Payslips'), ('payroll_adjustment', 'Payroll adjustments'), ('statutory_config', 'Statutory configuration'), ('policy_doc', 'Policy documents'), ('audit_log', 'Audit log'), ('notification', 'Notifications'), ('report', 'Reports'), ('dashboard_org', 'Organization-wide dashboard'), ('dashboard_department', 'Department dashboard'), ('dashboard_team', 'Team dashboard')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='userpermissionoverride',
            name='resource',
            field=models.CharField(choices=[('user', 'User accounts'), ('role', 'Roles and permissions'), ('department', 'Departments'), ('designation', 'Designations'), ('location', 'Locations'), ('org_settings', 'Organization settings'), ('employee', 'Employee records'), ('employee_document', 'Employee documents'), ('probation_review', 'Probation reviews'), ('asset', 'Assets'), ('asset_allocation', 'Asset allocations'), ('email_account', 'Company email accounts'), ('job_opening', 'Job openings'), ('candidate', 'Candidates'), ('application', 'Applications'), ('interview', 'Interviews'), ('interview_feedback', 'Interview feedback'), ('department_decision', 'Department hiring decisions'), ('offer', 'Offers'), ('hiring_workflow', 'Hiring workflow configuration'), ('onboarding', 'Onboarding'), ('offboarding', 'Offboarding'), ('letter', 'Employee letters'), ('attendance', 'Attendance'), ('regularization', 'Attendance regularization'), ('attendance_device', 'Biometric attendance devices'), ('leave_request', 'Leave requests'), ('leave_policy', 'Leave policy configuration'), ('salary', 'Salary structures'), ('payroll_run', 'Payroll runs'), ('payslip', 'Payslips'), ('payroll_adjustment', 'Payroll adjustments'), ('statutory_config', 'Statutory configuration'), ('policy_doc', 'Policy documents'), ('audit_log', 'Audit log'), ('notification', 'Notifications'), ('report', 'Reports'), ('dashboard_org', 'Organization-wide dashboard'), ('dashboard_department', 'Department dashboard'), ('dashboard_team', 'Team dashboard')], max_length=40),
        ),
    ]
