# Generated by Django 5.1.5 on 2026-09-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarystructure',
            name='esi_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='gratuity_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='pf_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='pt_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='tds_applicable',
            field=models.BooleanField(default=True),
        ),
    ]
