# Generated by Django 5.1.5 on 2026-09-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_salarystructure_esi_applicable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='attendance_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
