# Generated by Django 5.1.5 on 2026-09-09 06:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_designation_uniq_designation_title_department_and_more'),
        ('payroll', '0002_remove_payrollrun_uniq_payroll_run_per_period_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payrollrun',
            name='uniq_payroll_run_per_period',
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organization', 'period_year', 'period_month', 'location', 'run_type', 'sequence'), name='uniq_payroll_run_per_period', nulls_distinct=False),
        ),
    ]
