# Generated by Django 5.1.5 on 2026-09-02 09:28

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_annual_ctc'),
        ('payroll', '0003_payslip_attendance_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolladjustment',
            name='kind',
            field=models.CharField(choices=[('bonus', 'Bonus'), ('incentive', 'Incentive'), ('arrear', 'Arrears'), ('advance_recovery', 'Advance recovery'), ('loan_recovery', 'Loan EMI recovery'), ('reimbursement', 'Reimbursement'), ('other_earning', 'Other earning'), ('other_deduction', 'Other deduction'), ('deferred_release', 'Deferred package release')], max_length=30),
        ),
        migrations.CreateModel(
            name='EmployeePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('package_type', models.CharField(choices=[('monthly_plus_deferred', 'Monthly fixed + deferred amount'), ('year_wise', 'Year-wise package'), ('period_wise', 'Custom period-wise package'), ('milestone', 'Milestone / completion-based release')], default='period_wise', max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On hold'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('bond_start_date', models.DateField(blank=True, null=True)),
                ('bond_end_date', models.DateField(blank=True, null=True)),
                ('bond_required_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='employees.employee')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='payroll.employeepackage')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageDeferral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('label', models.CharField(default='Deferred amount', max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('condition_type', models.CharField(choices=[('after_months', 'After completing N months'), ('on_date', 'On a specific date'), ('bond_completion', 'Completion of bond/service period'), ('manual', 'Manual approval'), ('other', 'Other configured condition')], default='after_months', max_length=20)),
                ('condition_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('eligible_on', models.DateField(blank=True, null=True)),
                ('condition_note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending completion'), ('eligible', 'Eligible - pending approval'), ('approved', 'Approved - scheduled for payroll'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('on_hold', 'On hold'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deferrals', to='payroll.employeepackage')),
                ('released_in_adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payroll.payrolladjustment')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['eligible_on', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackagePeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('label', models.CharField(max_length=80)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='payroll.employeepackage')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'start_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='employeepackage',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='ck_package_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='employeepackage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('status__in', ['active', 'on_hold'])), fields=('employee',), name='uniq_live_package_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='packageperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='ck_package_period_dates_ordered'),
        ),
    ]
