# Generated by Django 5.1.5 on 2026-08-12 09:54

import apps.statutory.models
import django.contrib.postgres.constraints
import django.db.models.deletion
import uuid
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # The overlap constraint mixes equality on varchar columns (statute,
        # jurisdiction, regime) with range overlap on the effective dates inside
        # a single GiST index. GiST has no default operator class for scalar
        # types, so btree_gist is required — without it the constraint cannot be
        # created at all.
        #
        # btree_gist is a trusted extension in PostgreSQL 13+, so the database
        # owner installs it without needing superuser rights.
        BtreeGistExtension(),
        migrations.CreateModel(
            name='StatutoryRuleSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('statute', models.CharField(choices=[('pf', 'Provident Fund'), ('esi', "Employees' State Insurance"), ('pt', 'Professional Tax'), ('gratuity', 'Gratuity'), ('income_tax', 'Income Tax / TDS')], db_index=True, max_length=20)),
                ('jurisdiction', models.CharField(blank=True, db_index=True, help_text='State code for Professional Tax. Empty for national statutes.', max_length=8)),
                ('regime', models.CharField(blank=True, help_text="'old' / 'new' for income tax. Empty where not applicable.", max_length=16)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, help_text='NULL = still in force. Inclusive.', null=True)),
                ('financial_year', models.CharField(blank=True, db_index=True, help_text='e.g. "2025-2026".', max_length=9)),
                ('rule_version', models.CharField(help_text="Selects the implementation class, e.g. 'income_tax.v2'. The class declares which parameters it requires.", max_length=40)),
                ('parameters', models.JSONField(default=dict, help_text='Rates, thresholds, slabs, caps, eligibility parameters.')),
                ('source_citation', models.CharField(blank=True, help_text='Statute, section, notification or circular these values come from.', max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('retrieved_on', models.DateField(blank=True, null=True)),
                ('assumptions', models.JSONField(blank=True, default=list, help_text='Stated limits of applicability.')),
                ('verification_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], db_index=True, default='draft', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_note', models.TextField(blank=True, help_text='What the verifier checked these values against.')),
                ('rejection_reason', models.TextField(blank=True)),
                ('was_self_verified', models.BooleanField(default=False, help_text='Verified by the same person who edited it, under the exceptional path. Permanent — never cleared, so the exception stays visible for the life of the rule set.')),
                ('self_verification_reason', models.TextField(blank=True)),
                ('checksum', models.CharField(blank=True, editable=False, max_length=64)),
                ('verified_checksum', models.CharField(blank=True, editable=False, max_length=64)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['statute', 'jurisdiction', '-effective_from'],
                'indexes': [models.Index(fields=['statute', 'jurisdiction', 'effective_from'], name='statutory_s_statute_421dea_idx'), models.Index(fields=['verification_status', 'statute'], name='statutory_s_verific_79d9c6_idx')],
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('verification_status__in', ['verified', 'superseded']), ('is_active', True)), expressions=[('statute', '='), ('jurisdiction', '='), ('regime', '='), (apps.statutory.models.DateRange(models.F('effective_from'), models.F('effective_to'), models.Value('[]')), '&&')], name='excl_ruleset_no_overlapping_in_force'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ck_ruleset_effective_range_ordered')],
            },
        ),
    ]
