# Generated by Django 5.1.5 on 2026-09-09 06:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
        ('organization', '0002_remove_designation_uniq_designation_title_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='code',
            field=models.SlugField(max_length=40),
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_leavetype_org_code'),
        ),
    ]
