# Generated by Django 5.1.5 on 2026-08-25 05:50

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_annual_ctc'),
        ('leave', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepolicy',
            name='accrual_per_month',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='probation_unpaid',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LeaveSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('leave_year_start_month', models.PositiveSmallIntegerField(default=1)),
                ('long_leave_threshold_days', models.PositiveSmallIntegerField(default=3)),
                ('long_leave_notice_days', models.PositiveSmallIntegerField(default=30)),
                ('single_day_notice_days', models.PositiveSmallIntegerField(default=3)),
                ('general_notice_days', models.PositiveSmallIntegerField(default=7)),
                ('emergency_window_hours', models.PositiveSmallIntegerField(default=24)),
                ('probation_leave_unpaid', models.BooleanField(default=True)),
                ('short_leave_hours_per_day', models.DecimalField(decimal_places=1, default=Decimal('3'), max_digits=3)),
                ('absence_flag_days', models.PositiveSmallIntegerField(default=3)),
                ('holiday_work_double_pay', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'leave settings',
            },
        ),
        migrations.CreateModel(
            name='HolidayWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('date', models.DateField(db_index=True)),
                ('holiday_name', models.CharField(blank=True, max_length=140)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_work_days', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='uniq_holiday_work_per_day')],
            },
        ),
        migrations.CreateModel(
            name='ShortLeave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('date', models.DateField(db_index=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_leaves', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='uniq_short_leave_per_day')],
            },
        ),
        migrations.CreateModel(
            name='ShortLeaveConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('hours', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5)),
                ('days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=4)),
                ('deducted_days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=4)),
                ('lop_days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=4)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_leave_conversions', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'year', 'month'), name='uniq_short_leave_conversion')],
            },
        ),
    ]
