# Generated by Django 5.1.5 on 2026-09-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_restage_inflight_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepolicy',
            name='accrues_during_probation',
            field=models.BooleanField(default=False),
        ),
    ]
