# Generated by Django 5.1.5 on 2026-09-08 12:05

import apps.onboarding.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=140)),
                ('letter_type', models.CharField(choices=[('offer', 'Offer letter'), ('appointment', 'Appointment letter'), ('joining', 'Joining letter'), ('confirmation', 'Confirmation letter'), ('extension', 'Probation extension letter'), ('experience', 'Experience letter'), ('relieving', 'Relieving letter'), ('warning', 'Warning letter'), ('other', 'Other')], db_index=True, max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('body_html', models.TextField()),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['letter_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('letter_type', models.CharField(choices=[('offer', 'Offer letter'), ('appointment', 'Appointment letter'), ('joining', 'Joining letter'), ('confirmation', 'Confirmation letter'), ('extension', 'Probation extension letter'), ('experience', 'Experience letter'), ('relieving', 'Relieving letter'), ('warning', 'Warning letter'), ('other', 'Other')], db_index=True, max_length=30)),
                ('template_name', models.CharField(blank=True, max_length=140)),
                ('template_version', models.PositiveSmallIntegerField(default=1)),
                ('subject', models.CharField(max_length=200)),
                ('body_html', models.TextField(blank=True)),
                ('merge_context', models.JSONField(blank=True, default=dict)),
                ('pdf_file', models.FileField(blank=True, max_length=255, null=True, upload_to=apps.onboarding.models.letter_path)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('acknowledged', 'Acknowledged'), ('revoked', 'Revoked')], db_index=True, default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='employees.employee')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letters', to='onboarding.lettertemplate')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('employment_type', models.CharField(blank=True, max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_templates', to='organization.department')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeOnboarding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('template_name', models.CharField(blank=True, max_length=140)),
                ('joining_date', models.DateField()),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='in_progress', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='employees.employee')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboardings', to='onboarding.onboardingtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTemplateItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('kind', models.CharField(choices=[('document', 'Document to collect'), ('task', 'Task to complete'), ('account', 'Account or access to provision'), ('asset', 'Asset to allocate'), ('acknowledgement', 'Policy to acknowledge')], default='task', max_length=20)),
                ('owner', models.CharField(choices=[('hr', 'HR'), ('manager', 'Reporting manager'), ('employee', 'The employee'), ('department_head', 'Department head'), ('admin', 'Administrator')], default='hr', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('due_offset_days', models.SmallIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_items', to='employees.documenttype')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.organization')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='onboarding.onboardingtemplate')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['template', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('kind', models.CharField(choices=[('document', 'Document to collect'), ('task', 'Task to complete'), ('account', 'Account or access to provision'), ('asset', 'Asset to allocate'), ('acknowledgement', 'Policy to acknowledge')], default='task', max_length=20)),
                ('owner', models.CharField(choices=[('hr', 'HR'), ('manager', 'Reporting manager'), ('employee', 'The employee'), ('department_head', 'Department head'), ('admin', 'Administrator')], default='hr', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('submitted', 'Submitted, awaiting verification'), ('completed', 'Completed'), ('waived', 'Waived'), ('blocked', 'Blocked')], db_index=True, default='pending', max_length=20)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to=apps.onboarding.models.onboarding_item_path)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_items_assigned', to='employees.employee')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_items', to='employees.employeedocument')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employees.documenttype')),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='onboarding.employeeonboarding')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='onboarding.onboardingtemplateitem')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddConstraint(
            model_name='lettertemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('letter_type',), name='uniq_default_letter_template_per_type'),
        ),
        migrations.AddIndex(
            model_name='employeeletter',
            index=models.Index(fields=['employee', 'letter_type'], name='onboarding__employe_20143e_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeonboarding',
            index=models.Index(fields=['status', 'joining_date'], name='onboarding__status_1e4800_idx'),
        ),
        migrations.AddConstraint(
            model_name='onboardingtemplateitem',
            constraint=models.UniqueConstraint(fields=('template', 'order'), name='uniq_onboarding_item_order_per_template'),
        ),
        migrations.AddIndex(
            model_name='onboardingitem',
            index=models.Index(fields=['onboarding', 'status'], name='onboarding__onboard_45bf0e_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingitem',
            index=models.Index(fields=['status', 'due_date'], name='onboarding__status_6c6618_idx'),
        ),
    ]
