# Generated by Django 5.1.5 on 2026-08-17 10:19

import apps.onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeletter',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.onboarding.models.letter_path),
        ),
        migrations.AlterField(
            model_name='onboardingitem',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.onboarding.models.onboarding_item_path),
        ),
    ]
