# Generated by Django 5.1.5 on 2026-09-09 06:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
        ('organization', '0002_remove_designation_uniq_designation_title_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lettertemplate',
            name='uniq_default_letter_template_per_type',
        ),
        migrations.AddConstraint(
            model_name='lettertemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('organization', 'letter_type'), name='uniq_default_letter_template_per_type'),
        ),
    ]
