# Generated by Django 5.1.5 on 2026-08-17 10:19

import apps.offboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitclearanceitem',
            name='evidence',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.offboarding.models.clearance_evidence_path),
        ),
    ]
