# Generated by Django 5.1.5 on 2026-09-08 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_email', models.CharField(blank=True, max_length=254)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('approve', 'Approved'), ('reject', 'Rejected'), ('override', 'Overridden'), ('recommend', 'Recommended'), ('reverse', 'Reversed'), ('allocate', 'Allocated'), ('return', 'Returned'), ('login', 'Signed in'), ('login_failed', 'Sign-in failed'), ('access_pii', 'Accessed sensitive data'), ('export', 'Exported data'), ('import', 'Imported'), ('permission_change', 'Permissions changed'), ('role_change', 'Roles changed'), ('credential_issue', 'Credential issued'), ('credential_view', 'Credential viewed')], db_index=True, max_length=30)),
                ('resource', models.CharField(blank=True, db_index=True, max_length=40)),
                ('entity_type', models.CharField(db_index=True, max_length=120)),
                ('entity_id', models.CharField(db_index=True, max_length=64)),
                ('entity_label', models.CharField(blank=True, help_text='Human-readable identifier captured at write time, so the log stays readable after the row is gone.', max_length=255)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
