# Generated by Django 5.1.5 on 2026-08-14 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('employees', '0005_probationreview_confirmation_letter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='subject_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='employees.employee'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['subject_employee', '-occurred_at'], name='audit_audit_subject_2f2ea5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource', '-occurred_at'], name='audit_audit_resourc_454315_idx'),
        ),
    ]
