# Generated by Django 5.1.5 on 2026-08-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_backfill_audit_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('approve', 'Approved'), ('reject', 'Rejected'), ('override', 'Overridden'), ('recommend', 'Recommended'), ('reverse', 'Reversed'), ('allocate', 'Allocated'), ('return', 'Returned'), ('login', 'Signed in'), ('login_failed', 'Sign-in failed'), ('access_pii', 'Accessed sensitive data'), ('export', 'Exported data'), ('import', 'Imported'), ('permission_change', 'Permissions changed'), ('role_change', 'Roles changed'), ('credential_issue', 'Credential issued'), ('credential_view', 'Credential viewed')], db_index=True, max_length=30),
        ),
    ]
