# Generated by Django 5.1.5 on 2026-08-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgsettings',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='org/'),
        ),
    ]
