# Generated by Django 5.1.5 on 2026-08-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_orgsettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='signature',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='org/'),
        ),
    ]
