# Generated by Django 5.1.5 on 2026-09-08 07:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_orgsettings_signature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=250)),
                ('slug', models.SlugField(max_length=63, unique=True)),
                ('logo', models.ImageField(blank=True, max_length=255, null=True, upload_to='org/')),
                ('favicon', models.ImageField(blank=True, max_length=255, null=True, upload_to='org/')),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=8)),
                ('country', models.CharField(default='IN', max_length=2)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('date_format', models.CharField(default='d M Y', max_length=32)),
                ('status', models.CharField(choices=[('pending_setup', 'Pending setup'), ('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], db_index=True, default='pending_setup', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('removed', 'Removed')], db_index=True, default='active', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organization.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='organizatio_user_id_5f60fd_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='uniq_membership_org_user'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('status', 'active')), fields=('user',), name='uniq_one_active_membership')],
            },
        ),
    ]
