# Generated by Django 5.1.5 on 2026-09-11 10:41

import apps.organization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_orgemailconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='favicon',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.organization.models.organization_asset_path),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.organization.models.organization_asset_path),
        ),
        migrations.AlterField(
            model_name='orgsettings',
            name='signature',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.organization.models.org_settings_asset_path),
        ),
    ]
