"""
Make `OrgSettings` a per-organization profile row.

Company identity (name, legal name, currency, timezone, logo) moves to
`Organization`; the statutory registrations, the financial year, the employee
code counter and the signatory stay here, because they are jurisdiction-shaped
and, in the counter's case, write-hot.

WHY THIS DELETES ROWS
---------------------
`organization` is a required one-to-one, and there is no defensible way to
guess which company an existing settings row belongs to -- the whole point of
the change is that "the organization" was previously implicit. The system is
pre-production (no deployments, no approved payroll run; see
docs/CUTOVER_STATUS.md), the only rows that exist are development and demo
seeds, and `OrgSettings.for_org()` recreates one on first access. So the rows
are dropped rather than migrated.

Hand-written rather than autogenerated: `makemigrations` prompts for a one-off
default when a non-null relation is added, and no default is correct here.

This migration is expected to be folded away when the migration history is
regenerated (plan stage 2i).
"""

from django.db import migrations, models
import django.db.models.deletion


def drop_untenanted_settings(apps, schema_editor):
    apps.get_model("organization", "OrgSettings").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0004_organization_organizationmembership"),
    ]

    operations = [
        migrations.RemoveField(model_name="orgsettings", name="name"),
        migrations.RemoveField(model_name="orgsettings", name="legal_name"),
        migrations.RemoveField(model_name="orgsettings", name="currency"),
        migrations.RemoveField(model_name="orgsettings", name="timezone"),
        migrations.RemoveField(model_name="orgsettings", name="logo"),
        # Before the required relation is added, not after: the table must be
        # empty for a non-null column with no default to be addable at all.
        migrations.RunPython(drop_untenanted_settings, migrations.RunPython.noop),
        migrations.AddField(
            model_name="orgsettings",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to="organization.organization",
            ),
            preserve_default=False,
        ),
    ]
