# Generated by Django 5.1.5 on 2026-09-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_orgemailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='purged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
