"""
The organization-aware foreign keys this database enforces.

GENERATED from the model registry on 2026-09-22 and then FROZEN: the
migrations in this app were written from exactly this list. `access.E018`
compares the live registry with it, so a new organization-owned FK that
has no composite constraint fails `manage.py check` until a migration and
an entry here are added together.
"""

#: (source table, fk column, target table, target pk column)
ORG_FK_EDGES: tuple[tuple[str, str, str, str], ...] = (
    ('accounts_rolepermission', 'role_id', 'accounts_role', 'id'),
    ('accounts_userrole', 'role_id', 'accounts_role', 'id'),
    ('assets_asset', 'category_id', 'assets_assetcategory', 'id'),
    ('assets_asset', 'location_id', 'organization_location', 'id'),
    ('assets_assetallocation', 'asset_id', 'assets_asset', 'id'),
    ('assets_assetallocation', 'employee_id', 'employees_employee', 'id'),
    ('assets_assetmaintenancelog', 'asset_id', 'assets_asset', 'id'),
    ('attendance_attendancedevice', 'location_id', 'organization_location', 'id'),
    ('attendance_attendancerecord', 'employee_id', 'employees_employee', 'id'),
    ('attendance_esslemployeelink', 'employee_id', 'employees_employee', 'id'),
    ('attendance_esslemployeelink', 'location_id', 'organization_location', 'id'),
    ('attendance_rawpunch', 'device_id', 'attendance_attendancedevice', 'id'),
    ('attendance_rawpunch', 'employee_id', 'employees_employee', 'id'),
    ('attendance_regularizationrequest', 'employee_id', 'employees_employee', 'id'),
    ('attendance_shiftrule', 'location_id', 'organization_location', 'id'),
    ('employees_emergencycontact', 'employee_id', 'employees_employee', 'id'),
    ('employees_employee', 'created_from_candidate_id', 'recruitment_candidate', 'id'),
    ('employees_employee', 'department_id', 'organization_department', 'id'),
    ('employees_employee', 'designation_id', 'organization_designation', 'id'),
    ('employees_employee', 'level_id', 'organization_employeelevel', 'id'),
    ('employees_employee', 'location_id', 'organization_location', 'id'),
    ('employees_employee', 'reporting_manager_id', 'employees_employee', 'id'),
    ('employees_employee', 'team_id', 'organization_team', 'id'),
    ('employees_employeeaddress', 'employee_id', 'employees_employee', 'id'),
    ('employees_employeedocument', 'document_type_id', 'employees_documenttype', 'id'),
    ('employees_employeedocument', 'employee_id', 'employees_employee', 'id'),
    ('employees_employeeeducation', 'employee_id', 'employees_employee', 'id'),
    ('employees_employeeexperience', 'employee_id', 'employees_employee', 'id'),
    ('employees_probationreview', 'confirmation_letter_id', 'onboarding_employeeletter', 'id'),
    ('employees_probationreview', 'employee_id', 'employees_employee', 'id'),
    ('employees_probationreview', 'reviewer_id', 'employees_employee', 'id'),
    ('imports_importbatch', 'job_opening_id', 'recruitment_jobopening', 'id'),
    ('imports_importrow', 'batch_id', 'imports_importbatch', 'id'),
    ('imports_importrow', 'created_employee_id', 'employees_employee', 'id'),
    ('imports_importrow', 'matched_candidate_id', 'recruitment_candidate', 'id'),
    ('itaccounts_companyemailaccount', 'employee_id', 'employees_employee', 'id'),
    ('leave_holiday', 'calendar_id', 'leave_holidaycalendar', 'id'),
    ('leave_holidaycalendar', 'location_id', 'organization_location', 'id'),
    ('leave_holidaywork', 'employee_id', 'employees_employee', 'id'),
    ('leave_leavebalance', 'employee_id', 'employees_employee', 'id'),
    ('leave_leavebalance', 'leave_type_id', 'leave_leavetype', 'id'),
    ('leave_leavepolicy', 'department_id', 'organization_department', 'id'),
    ('leave_leavepolicy', 'leave_type_id', 'leave_leavetype', 'id'),
    ('leave_leaverequest', 'employee_id', 'employees_employee', 'id'),
    ('leave_leaverequest', 'leave_type_id', 'leave_leavetype', 'id'),
    ('leave_leaverequest', 'policy_id', 'leave_leavepolicy', 'id'),
    ('leave_leavetransaction', 'employee_id', 'employees_employee', 'id'),
    ('leave_leavetransaction', 'leave_type_id', 'leave_leavetype', 'id'),
    ('leave_leavetransaction', 'request_id', 'leave_leaverequest', 'id'),
    ('leave_shortleave', 'employee_id', 'employees_employee', 'id'),
    ('leave_shortleaveconversion', 'employee_id', 'employees_employee', 'id'),
    ('notifications_notificationdelivery', 'notification_id', 'notifications_notification', 'id'),
    ('offboarding_clearancetemplate', 'department_id', 'organization_department', 'id'),
    ('offboarding_clearancetemplateitem', 'template_id', 'offboarding_clearancetemplate', 'id'),
    ('offboarding_exitclearanceitem', 'assigned_to_id', 'employees_employee', 'id'),
    ('offboarding_exitclearanceitem', 'exit_workflow_id', 'offboarding_exitworkflow', 'id'),
    ('offboarding_exitclearanceitem', 'source_item_id', 'offboarding_clearancetemplateitem', 'id'),
    ('offboarding_exitinterview', 'exit_workflow_id', 'offboarding_exitworkflow', 'id'),
    ('offboarding_exitworkflow', 'employee_id', 'employees_employee', 'id'),
    ('offboarding_exitworkflow', 'resignation_id', 'offboarding_resignationrequest', 'id'),
    ('offboarding_finalsettlement', 'exit_workflow_id', 'offboarding_exitworkflow', 'id'),
    ('offboarding_resignationrequest', 'employee_id', 'employees_employee', 'id'),
    ('onboarding_employeeletter', 'employee_id', 'employees_employee', 'id'),
    ('onboarding_employeeletter', 'template_id', 'onboarding_lettertemplate', 'id'),
    ('onboarding_employeeonboarding', 'employee_id', 'employees_employee', 'id'),
    ('onboarding_employeeonboarding', 'template_id', 'onboarding_onboardingtemplate', 'id'),
    ('onboarding_onboardingitem', 'assigned_to_id', 'employees_employee', 'id'),
    ('onboarding_onboardingitem', 'document_id', 'employees_employeedocument', 'id'),
    ('onboarding_onboardingitem', 'document_type_id', 'employees_documenttype', 'id'),
    ('onboarding_onboardingitem', 'onboarding_id', 'onboarding_employeeonboarding', 'id'),
    ('onboarding_onboardingitem', 'source_item_id', 'onboarding_onboardingtemplateitem', 'id'),
    ('onboarding_onboardingtemplate', 'department_id', 'organization_department', 'id'),
    ('onboarding_onboardingtemplateitem', 'document_type_id', 'employees_documenttype', 'id'),
    ('onboarding_onboardingtemplateitem', 'template_id', 'onboarding_onboardingtemplate', 'id'),
    ('organization_department', 'head_employee_id', 'employees_employee', 'id'),
    ('organization_department', 'parent_department_id', 'organization_department', 'id'),
    ('organization_designation', 'department_id', 'organization_department', 'id'),
    ('organization_team', 'department_id', 'organization_department', 'id'),
    ('organization_team', 'head_employee_id', 'employees_employee', 'id'),
    ('organization_team', 'parent_team_id', 'organization_team', 'id'),
    ('payroll_employeeloan', 'employee_id', 'employees_employee', 'id'),
    ('payroll_employeepackage', 'employee_id', 'employees_employee', 'id'),
    ('payroll_employeepackage', 'supersedes_id', 'payroll_employeepackage', 'id'),
    ('payroll_investmentdeclaration', 'employee_id', 'employees_employee', 'id'),
    ('payroll_packagedeferral', 'package_id', 'payroll_employeepackage', 'id'),
    ('payroll_packagedeferral', 'released_in_adjustment_id', 'payroll_payrolladjustment', 'id'),
    ('payroll_packageperiod', 'package_id', 'payroll_employeepackage', 'id'),
    ('payroll_payrolladjustment', 'employee_id', 'employees_employee', 'id'),
    ('payroll_payrolladjustment', 'payroll_run_id', 'payroll_payrollrun', 'id'),
    ('payroll_payrollrun', 'location_id', 'organization_location', 'id'),
    ('payroll_payslip', 'employee_id', 'employees_employee', 'id'),
    ('payroll_payslip', 'location_id', 'organization_location', 'id'),
    ('payroll_payslip', 'payroll_run_id', 'payroll_payrollrun', 'id'),
    ('payroll_payslip', 'salary_structure_id', 'payroll_salarystructure', 'id'),
    ('payroll_payslipline', 'component_id', 'payroll_salarycomponent', 'id'),
    ('payroll_payslipline', 'payslip_id', 'payroll_payslip', 'id'),
    ('payroll_reimbursementclaim', 'employee_id', 'employees_employee', 'id'),
    ('payroll_reimbursementclaim', 'paid_in_run_id', 'payroll_payrollrun', 'id'),
    ('payroll_salarystructure', 'employee_id', 'employees_employee', 'id'),
    ('payroll_salarystructureline', 'component_id', 'payroll_salarycomponent', 'id'),
    ('payroll_salarystructureline', 'salary_structure_id', 'payroll_salarystructure', 'id'),
    ('payroll_statutorycontribution', 'payslip_id', 'payroll_payslip', 'id'),
    ('recruitment_application', 'candidate_id', 'recruitment_candidate', 'id'),
    ('recruitment_application', 'current_stage_id', 'workflows_workflowstage', 'id'),
    ('recruitment_application', 'job_opening_id', 'recruitment_jobopening', 'id'),
    ('recruitment_applicationevent', 'application_id', 'recruitment_application', 'id'),
    ('recruitment_applicationevent', 'from_stage_id', 'workflows_workflowstage', 'id'),
    ('recruitment_applicationevent', 'to_stage_id', 'workflows_workflowstage', 'id'),
    ('recruitment_candidateexternalref', 'candidate_id', 'recruitment_candidate', 'id'),
    ('recruitment_candidatenotification', 'application_id', 'recruitment_application', 'id'),
    ('recruitment_candidatenotification', 'candidate_id', 'recruitment_candidate', 'id'),
    ('recruitment_candidatenotification', 'job_opening_id', 'recruitment_jobopening', 'id'),
    ('recruitment_candidaterejection', 'application_id', 'recruitment_application', 'id'),
    ('recruitment_candidaterejection', 'candidate_id', 'recruitment_candidate', 'id'),
    ('recruitment_candidaterejection', 'department_recommendation_id', 'recruitment_stagedecision', 'id'),
    ('recruitment_candidaterejection', 'rejection_stage_id', 'workflows_workflowstage', 'id'),
    ('recruitment_consentrecord', 'candidate_id', 'recruitment_candidate', 'id'),
    ('recruitment_consentrecord', 'origin_batch_id', 'imports_importbatch', 'id'),
    ('recruitment_decisionoverride', 'application_id', 'recruitment_application', 'id'),
    ('recruitment_decisionoverride', 'new_stage_id', 'workflows_workflowstage', 'id'),
    ('recruitment_decisionoverride', 'previous_stage_id', 'workflows_workflowstage', 'id'),
    ('recruitment_interview', 'application_id', 'recruitment_application', 'id'),
    ('recruitment_interview', 'interviewer_id', 'employees_employee', 'id'),
    ('recruitment_interview', 'stage_id', 'workflows_workflowstage', 'id'),
    ('recruitment_interviewfeedback', 'form_id', 'workflows_feedbackform', 'id'),
    ('recruitment_interviewfeedback', 'interview_id', 'recruitment_interview', 'id'),
    ('recruitment_interviewfeedback', 'submitted_by_id', 'employees_employee', 'id'),
    ('recruitment_interviewslotinvite', 'application_id', 'recruitment_application', 'id'),
    ('recruitment_interviewslotinvite', 'candidate_id', 'recruitment_candidate', 'id'),
    ('recruitment_interviewslotinvite', 'stage_id', 'workflows_workflowstage', 'id'),
    ('recruitment_jobopening', 'department_id', 'organization_department', 'id'),
    ('recruitment_jobopening', 'designation_id', 'organization_designation', 'id'),
    ('recruitment_jobopening', 'hiring_manager_id', 'employees_employee', 'id'),
    ('recruitment_jobopening', 'level_id', 'organization_employeelevel', 'id'),
    ('recruitment_jobopening', 'location_id', 'organization_location', 'id'),
    ('recruitment_jobopening', 'recruiter_id', 'employees_employee', 'id'),
    ('recruitment_jobopening', 'target_role_id', 'accounts_role', 'id'),
    ('recruitment_jobopening', 'workflow_id', 'workflows_hiringworkflow', 'id'),
    ('recruitment_offer', 'application_id', 'recruitment_application', 'id'),
    ('recruitment_offer', 'designation_id', 'organization_designation', 'id'),
    ('recruitment_offer', 'level_id', 'organization_employeelevel', 'id'),
    ('recruitment_offer', 'reporting_manager_id', 'employees_employee', 'id'),
    ('recruitment_stagedecision', 'application_id', 'recruitment_application', 'id'),
    ('recruitment_stagedecision', 'interview_id', 'recruitment_interview', 'id'),
    ('recruitment_stagedecision', 'stage_id', 'workflows_workflowstage', 'id'),
    ('workflows_feedbackfield', 'form_id', 'workflows_feedbackform', 'id'),
    ('workflows_stagetransition', 'from_stage_id', 'workflows_workflowstage', 'id'),
    ('workflows_stagetransition', 'to_stage_id', 'workflows_workflowstage', 'id'),
    ('workflows_workflowstage', 'feedback_form_id', 'workflows_feedbackform', 'id'),
    ('workflows_workflowstage', 'responsible_role_id', 'accounts_role', 'id'),
    ('workflows_workflowstage', 'workflow_id', 'workflows_hiringworkflow', 'id'),
)

#: Tables row-level security covers (tenant policy).
RLS_TENANT_TABLES: tuple[str, ...] = (
    'accounts_role',
    'accounts_rolepermission',
    'accounts_userpermissionoverride',
    'accounts_userrole',
    'assets_asset',
    'assets_assetallocation',
    'assets_assetcategory',
    'assets_assetmaintenancelog',
    'attendance_attendancedevice',
    'attendance_attendancerecord',
    'attendance_esslemployeelink',
    'attendance_esslsyncrun',
    'attendance_orgattendanceintegration',
    'attendance_rawpunch',
    'attendance_regularizationrequest',
    'attendance_shiftrule',
    'employees_documenttype',
    'employees_emergencycontact',
    'employees_employee',
    'employees_employeeaddress',
    'employees_employeedocument',
    'employees_employeeeducation',
    'employees_employeeexperience',
    'employees_probationreview',
    'imports_importbatch',
    'imports_importrow',
    'itaccounts_companyemailaccount',
    'leave_holiday',
    'leave_holidaycalendar',
    'leave_holidaywork',
    'leave_leavebalance',
    'leave_leavepolicy',
    'leave_leaverequest',
    'leave_leavesettings',
    'leave_leavetransaction',
    'leave_leavetype',
    'leave_shortleave',
    'leave_shortleaveconversion',
    'notifications_notification',
    'notifications_notificationdelivery',
    'notifications_notificationpreference',
    'offboarding_clearancetemplate',
    'offboarding_clearancetemplateitem',
    'offboarding_exitclearanceitem',
    'offboarding_exitinterview',
    'offboarding_exitworkflow',
    'offboarding_finalsettlement',
    'offboarding_resignationrequest',
    'onboarding_employeeletter',
    'onboarding_employeeonboarding',
    'onboarding_lettertemplate',
    'onboarding_onboardingitem',
    'onboarding_onboardingtemplate',
    'onboarding_onboardingtemplateitem',
    'organization_department',
    'organization_designation',
    'organization_employeelevel',
    'organization_location',
    'organization_orgemailtemplate',
    'organization_team',
    'payroll_employeeloan',
    'payroll_employeepackage',
    'payroll_investmentdeclaration',
    'payroll_packagedeferral',
    'payroll_packageperiod',
    'payroll_payrolladjustment',
    'payroll_payrollrun',
    'payroll_payslip',
    'payroll_payslipline',
    'payroll_reimbursementclaim',
    'payroll_salarycomponent',
    'payroll_salarystructure',
    'payroll_salarystructureline',
    'payroll_statutorycontribution',
    'platform_supportgrant',
    'recruitment_application',
    'recruitment_applicationevent',
    'recruitment_candidate',
    'recruitment_candidateexternalref',
    'recruitment_candidatenotification',
    'recruitment_candidaterejection',
    'recruitment_consentrecord',
    'recruitment_decisionoverride',
    'recruitment_interview',
    'recruitment_interviewfeedback',
    'recruitment_interviewslotinvite',
    'recruitment_jobopening',
    'recruitment_offer',
    'recruitment_stagedecision',
    'reporting_metricsnapshot',
    'workflows_feedbackfield',
    'workflows_feedbackform',
    'workflows_hiringworkflow',
    'workflows_stagetransition',
    'workflows_workflowstage',
    'organization_orgsettings',
    'organization_orgemailconfig',
)

RLS_MEMBERSHIP_TABLE = 'organization_organizationmembership'
RLS_AUDIT_TABLE = "audit_auditlog"
RLS_SUBSCRIPTION_TABLE = "platform_subscription"
