# Generated by Django 5.1.5 on 2026-09-09 06:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='code',
            field=models.SlugField(max_length=40),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('organization', 'asset_tag'), name='uniq_asset_org_tag'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_assetcategory_org_code'),
        ),
    ]
