# Generated by Django 5.1.5 on 2026-08-27 06:58

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0008_employee_annual_ctc'),
        ('organization', '0002_alter_orgsettings_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=120)),
                ('serial_number', models.CharField(max_length=64, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(choices=[('never', 'Never synced'), ('ok', 'OK'), ('failed', 'Failed')], default='never', max_length=12)),
                ('last_sync_error', models.CharField(blank=True, max_length=2000)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_devices', to='organization.location')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EsslEmployeeLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('essl_user_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='essl_link', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['essl_user_id'],
            },
        ),
        migrations.CreateModel(
            name='EsslSyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('kind', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Sync now'), ('range', 'Date range')], max_length=12)),
                ('range_from', models.DateField(blank=True, null=True)),
                ('range_to', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('partial', 'Completed with errors'), ('failed', 'Failed')], default='running', max_length=12)),
                ('devices_total', models.PositiveSmallIntegerField(default=0)),
                ('devices_failed', models.PositiveSmallIntegerField(default=0)),
                ('punches_fetched', models.PositiveIntegerField(default=0)),
                ('punches_created', models.PositiveIntegerField(default=0)),
                ('punches_duplicate', models.PositiveIntegerField(default=0)),
                ('punches_unmapped', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RegularizationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('date', models.DateField()),
                ('proposed_in', models.DateTimeField(blank=True, null=True)),
                ('proposed_out', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularizations', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('date', models.DateField(db_index=True)),
                ('first_in', models.DateTimeField(blank=True, null=True)),
                ('last_out', models.DateTimeField(blank=True, null=True)),
                ('worked_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('present', 'Present'), ('half_day', 'Half day'), ('absent', 'Absent'), ('on_leave', 'On leave'), ('holiday', 'Holiday'), ('weekly_off', 'Weekly off')], max_length=12)),
                ('is_late', models.BooleanField(default=False)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('device', 'Device'), ('manual', 'Manual correction'), ('regularized', 'Regularized')], default='device', max_length=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['employee', 'date'], name='attendance__employe_b6a945_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('employee', 'date'), name='uniq_attendance_day_active')],
            },
        ),
        migrations.CreateModel(
            name='RawPunch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('essl_user_id', models.CharField(max_length=32)),
                ('punched_at', models.DateTimeField()),
                ('raw', models.CharField(blank=True, max_length=512)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punches', to='attendance.attendancedevice')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_punches', to='employees.employee')),
            ],
            options={
                'ordering': ['-punched_at'],
                'indexes': [models.Index(fields=['essl_user_id', 'punched_at'], name='attendance__essl_us_275989_idx'), models.Index(fields=['employee', 'punched_at'], name='attendance__employe_1dcd30_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'essl_user_id', 'punched_at'), name='uniq_punch_per_device_user_moment')],
            },
        ),
        migrations.CreateModel(
            name='ShiftRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('grace_minutes', models.PositiveSmallIntegerField(default=15)),
                ('allowed_late_per_month', models.PositiveSmallIntegerField(default=3)),
                ('half_day_below_hours', models.DecimalField(decimal_places=1, default=Decimal('4.5'), max_digits=4)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_rule', to='organization.location')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['location__name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('location__isnull', True)), fields=('location',), name='uniq_default_shift_rule')],
            },
        ),
    ]
