# Generated by Django 5.1.5 on 2026-08-31 07:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from decimal import Decimal

from django.db import migrations, models


def backfill(apps, schema_editor):
    """
    Preserve today's meaning, change nothing visible.

    Every existing late was a counted late under the old policy, so the new
    tally field starts equal to is_late — monthly counts stay identical and no
    status is rewritten. queryset.update() skips signals deliberately: this is
    a definition backfill, not user activity, and must not spray audit rows.

    Each existing shift rule's full-day hours are its own span, matching the
    policy decision that worked time (first punch to last) includes breaks.
    """
    AttendanceRecord = apps.get_model("attendance", "AttendanceRecord")
    AttendanceRecord.objects.filter(is_late=True).update(late_counted=True)

    ShiftRule = apps.get_model("attendance", "ShiftRule")
    for rule in ShiftRule.objects.all():
        span = (
            rule.end_time.hour * 60 + rule.end_time.minute
            - rule.start_time.hour * 60 - rule.start_time.minute
        )
        rule.full_day_hours = Decimal(span) / Decimal(60)
        rule.save(update_fields=["full_day_hours"])


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_schedule_essl_sync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='late_counted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftrule',
            name='full_day_hours',
            field=models.DecimalField(decimal_places=1, default=Decimal('9.0'), max_digits=4),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
