# Generated by Django 5.1.5 on 2026-09-09 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('employees', '0003_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shiftrule',
            name='uniq_default_shift_rule',
        ),
        migrations.AlterField(
            model_name='attendancedevice',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='esslemployeelink',
            name='essl_user_id',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='shiftrule',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_rule', to='organization.location'),
        ),
        migrations.AddConstraint(
            model_name='attendancedevice',
            constraint=models.UniqueConstraint(fields=('organization', 'serial_number'), name='uniq_device_org_serial'),
        ),
        migrations.AddConstraint(
            model_name='esslemployeelink',
            constraint=models.UniqueConstraint(fields=('organization', 'essl_user_id'), name='uniq_essllink_org_user_id'),
        ),
        migrations.AddConstraint(
            model_name='shiftrule',
            constraint=models.UniqueConstraint(fields=('organization', 'location'), name='uniq_shift_rule_org_location'),
        ),
        migrations.AddConstraint(
            model_name='shiftrule',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', True)), fields=('organization',), name='uniq_default_shift_rule'),
        ),
    ]
