# Generated by Django 5.1.5 on 2026-09-04 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancerecord_late_counted_and_more'),
        ('employees', '0008_employee_annual_ctc'),
        ('organization', '0003_orgsettings_signature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='esslemployeelink',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essl_links', to='organization.location'),
        ),
        migrations.AlterField(
            model_name='esslemployeelink',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essl_links', to='employees.employee'),
        ),
        migrations.AddIndex(
            model_name='esslemployeelink',
            index=models.Index(fields=['employee', 'is_active'], name='attendance__employe_0c8408_idx'),
        ),
    ]
