# Generated by Django 5.1.5 on 2026-09-11 09:46

import core.fields
import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_shiftrule_uniq_default_shift_rule_and_more'),
        ('organization', '0003_orgemailconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgAttendanceIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('base_url', models.URLField(blank=True, max_length=400)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('password', core.fields.EncryptedCharField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organization attendance integration',
                'constraints': [models.UniqueConstraint(fields=('organization',), name='uniq_attendance_integration_per_org')],
            },
            bases=(core.models.OrgStampingMixin, models.Model),
        ),
    ]
