# Generated by Django 5.1.5 on 2026-08-12 11:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('kind', models.CharField(choices=[('applied', 'Applied'), ('stage_changed', 'Stage changed'), ('verified', 'HR verified'), ('info_requested', 'More information requested'), ('interview_scheduled', 'Interview scheduled'), ('interview_completed', 'Interview completed'), ('feedback_submitted', 'Feedback submitted'), ('recommendation', 'Department recommendation'), ('hr_decision', 'HR Head decision'), ('rejected', 'Rejected'), ('override', 'Administrative override'), ('offer_created', 'Offer created'), ('offer_sent', 'Offer sent'), ('offer_responded', 'Offer responded to'), ('converted', 'Converted to employee')], db_index=True, max_length=30)),
                ('decision', models.CharField(blank=True, max_length=30)),
                ('actor_label', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('current_employer', models.CharField(blank=True, max_length=160)),
                ('total_experience_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('expected_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notice_period_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='recruitment/resumes/')),
                ('source', models.CharField(default='direct', max_length=40)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('final_decision_at', models.DateTimeField(blank=True, null=True)),
                ('retention_until', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateRejection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('rejected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField()),
                ('history_snapshot', models.JSONField(blank=True, default=dict)),
                ('is_overridden', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-rejected_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('overridden_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('previous_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('reason', models.TextField()),
            ],
            options={
                'ordering': ['-overridden_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=45)),
                ('scheduled_end', models.DateTimeField(editable=False)),
                ('mode', models.CharField(default='in_person', max_length=20)),
                ('location_or_link', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'Candidate did not attend')], db_index=True, default='scheduled', max_length=20)),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('answers', models.JSONField(default=dict)),
                ('strengths', models.TextField(blank=True)),
                ('concerns', models.TextField(blank=True)),
                ('recommendation', models.CharField(choices=[('strong_hire', 'Strong hire'), ('hire', 'Hire'), ('hold', 'Hold'), ('no hire', 'No hire')], max_length=20)),
                ('overall_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('openings_count', models.PositiveSmallIntegerField(default=1)),
                ('employment_type', models.CharField(default='full_time', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('on_hold', 'On hold'), ('closed', 'Closed'), ('filled', 'Filled')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('offered_ctc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('joining_date', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StageDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('decision', models.CharField(db_index=True, max_length=30)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rationale', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('active', 'In progress'), ('selected', 'Selected'), ('offer_sent', 'Offer sent'), ('offer_accepted', 'Offer accepted'), ('offer_declined', 'Offer declined'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='active', max_length=20)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
