# Generated by Django 5.1.5 on 2026-08-12 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('employees', '0002_initial'),
        ('organization', '0001_initial'),
        ('recruitment', '0001_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='current_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='workflows.workflowstage'),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='recruitment.application'),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='from_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflows.workflowstage'),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='to_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflows.workflowstage'),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='recruitment.candidate'),
        ),
        migrations.AddField(
            model_name='candidaterejection',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rejection', to='recruitment.application'),
        ),
        migrations.AddField(
            model_name='candidaterejection',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rejections', to='recruitment.candidate'),
        ),
        migrations.AddField(
            model_name='candidaterejection',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidaterejection',
            name='rejected_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidaterejection',
            name='rejection_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflows.workflowstage'),
        ),
        migrations.AddField(
            model_name='candidaterejection',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisionoverride',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='recruitment.application'),
        ),
        migrations.AddField(
            model_name='decisionoverride',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisionoverride',
            name='overridden_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisionoverride',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment.application'),
        ),
        migrations.AddField(
            model_name='interview',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interviews_conducted', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='interview',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interviews', to='workflows.workflowstage'),
        ),
        migrations.AddField(
            model_name='interview',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='workflows.feedbackform'),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='interview',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='recruitment.interview'),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_submitted', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_openings', to='organization.department'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_openings', to='organization.designation'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='hiring_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_as_hiring_manager', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_openings', to='organization.employeelevel'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_openings', to='organization.location'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_as_recruiter', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='target_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_openings', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_openings', to='workflows.hiringworkflow'),
        ),
        migrations.AddField(
            model_name='application',
            name='job_opening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='recruitment.jobopening'),
        ),
        migrations.AddField(
            model_name='offer',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='offer', to='recruitment.application'),
        ),
        migrations.AddField(
            model_name='offer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='organization.designation'),
        ),
        migrations.AddField(
            model_name='offer',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='organization.employeelevel'),
        ),
        migrations.AddField(
            model_name='offer',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_as_manager', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='offer',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stagedecision',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_decisions', to='recruitment.application'),
        ),
        migrations.AddField(
            model_name='stagedecision',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stagedecision',
            name='decided_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stagedecision',
            name='interview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='recruitment.interview'),
        ),
        migrations.AddField(
            model_name='stagedecision',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='workflows.workflowstage'),
        ),
        migrations.AddField(
            model_name='stagedecision',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidaterejection',
            name='department_recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recruitment.stagedecision'),
        ),
        migrations.AddIndex(
            model_name='applicationevent',
            index=models.Index(fields=['application', 'created_at'], name='recruitment_applica_a61cde_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('email',), name='uniq_active_candidate_email'),
        ),
        migrations.AddConstraint(
            model_name='decisionoverride',
            constraint=models.CheckConstraint(condition=models.Q(('reason__regex', '\\S{20,}')), name='ck_override_reason_minimum_length'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['interviewer', 'scheduled_at'], name='recruitment_intervi_72e1da_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['application', 'stage'], name='recruitment_applica_43fa8d_idx'),
        ),
        migrations.AddIndex(
            model_name='jobopening',
            index=models.Index(fields=['status', 'department'], name='recruitment_status_1f5979_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job_opening', 'current_stage', 'status'], name='recruitment_job_ope_e47086_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('candidate', 'job_opening'), name='uniq_application_per_candidate_job'),
        ),
        migrations.AddIndex(
            model_name='stagedecision',
            index=models.Index(fields=['application', 'stage'], name='recruitment_applica_2760bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidaterejection',
            constraint=models.CheckConstraint(condition=models.Q(('reason__regex', '\\S{20,}')), name='ck_rejection_reason_minimum_length'),
        ),
    ]
