# Generated by Django 5.1.5 on 2026-09-09 06:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_designation_uniq_designation_title_department_and_more'),
        ('recruitment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candidate',
            name='uniq_active_candidate_email_norm',
        ),
        migrations.RemoveConstraint(
            model_name='candidateexternalref',
            name='uniq_active_external_ref',
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organization', 'email_normalized'), name='uniq_active_candidate_email_norm'),
        ),
        migrations.AddConstraint(
            model_name='candidateexternalref',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organization', 'source', 'external_id'), name='uniq_active_external_ref'),
        ),
    ]
