# Generated by Django 5.1.5 on 2026-09-11 10:41

import apps.recruitment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_remove_candidate_uniq_active_candidate_email_norm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.recruitment.models.candidate_resume_path),
        ),
        migrations.AlterField(
            model_name='offer',
            name='letter_pdf',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=apps.recruitment.models.offer_letter_path),
        ),
    ]
