# Generated by Django 5.1.5 on 2026-08-12 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candidaterejection',
            name='ck_rejection_reason_minimum_length',
        ),
        migrations.RemoveConstraint(
            model_name='decisionoverride',
            name='ck_override_reason_minimum_length',
        ),
        migrations.AddConstraint(
            model_name='candidaterejection',
            constraint=models.CheckConstraint(condition=models.Q(('reason__length__gte', 20)), name='ck_rejection_reason_minimum_length'),
        ),
        migrations.AddConstraint(
            model_name='decisionoverride',
            constraint=models.CheckConstraint(condition=models.Q(('reason__length__gte', 20)), name='ck_override_reason_minimum_length'),
        ),
    ]
