# Generated by Django 5.1.5 on 2026-08-12 11:51

import apps.recruitment.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    The interviewer double-booking constraint.

    GiST cannot index the `=` operator on a uuid on its own — that is what
    btree_gist supplies. Without the extension the constraint below simply
    fails to create, so it is declared here rather than assumed from another
    app's migration: this app must be installable on a fresh database by
    itself.
    """

    dependencies = [
        ('employees', '0002_initial'),
        ('recruitment', '0003_remove_candidaterejection_ck_rejection_reason_minimum_length_and_more'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.AddConstraint(
            model_name='interview',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_active', True), ('status__in', ['scheduled', 'rescheduled'])), expressions=[('interviewer', '='), (apps.recruitment.models.TsTzRange('scheduled_at', 'scheduled_end', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='excl_interviewer_double_booking'),
        ),
    ]
