# Generated by Django 5.1.5 on 2026-08-13 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_interview_excl_interviewer_double_booking'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionoverride',
            name='new_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflows.workflowstage'),
        ),
        migrations.AddField(
            model_name='decisionoverride',
            name='previous_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflows.workflowstage'),
        ),
    ]
