# Generated by Django 5.1.5 on 2026-08-17 06:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_candidate_identity_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('basis', models.CharField(choices=[('consent', 'Consent given directly'), ('voluntarily_provided', 'Voluntarily provided (s.7(a))'), ('employer_subscription', 'Employer platform subscription'), ('legacy_unrecorded', 'Legacy — basis not recorded')], max_length=32)),
                ('recorded_via', models.CharField(max_length=40)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('notice_sent_at', models.DateTimeField(blank=True, null=True)),
                ('affirmed_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='recruitment.candidate')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['candidate', '-recorded_at'], name='recruitment_candida_43ea3d_idx'), models.Index(fields=['basis', 'affirmed_at'], name='recruitment_basis_eea4f1_idx')],
            },
        ),
    ]
