# Generated by Django 5.1.5 on 2026-08-17 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
        ('recruitment', '0011_schedule_retention_purge'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentrecord',
            name='origin_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consent_records', to='imports.importbatch'),
        ),
    ]
