# Generated by Django 5.1.5 on 2026-08-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0012_consent_origin_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='recruitment/resumes/'),
        ),
    ]
