# Generated by Django 5.1.5 on 2026-08-18 10:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0013_alter_candidate_resume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='form_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='candidate',
            name='profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='application_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='application_token',
            field=models.CharField(db_index=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='external_form_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='external_form_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='external_form_provider',
            field=models.CharField(blank=True, default='hosted', max_length=20),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='external_form_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='external_form_url',
            field=models.URLField(blank=True, max_length=400),
        ),
        migrations.CreateModel(
            name='CandidateNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('kind', models.CharField(choices=[('application_received', 'Application received'), ('hr_verification_passed', 'HR verification passed'), ('hr_verification_rejected', 'HR verification rejected'), ('interview_scheduled', 'Interview scheduled'), ('interview_rescheduled', 'Interview rescheduled'), ('interview_cancelled', 'Interview cancelled'), ('interview_selected', 'Selected for next round'), ('interview_not_selected', 'Not selected after interview'), ('interview_on_hold', 'Application under further review'), ('department_decision', 'Department decision'), ('final_selection', 'Final selection'), ('final_rejection', 'Final rejection'), ('offer_sent', 'Offer sent'), ('offer_accepted', 'Offer accepted'), ('offer_declined', 'Offer declined')], db_index=True, max_length=40)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped — no email address')], db_index=True, default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('dedupe_key', models.CharField(max_length=200, unique=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_notifications', to='recruitment.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='recruitment.candidate')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_notifications', to='recruitment.jobopening')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', '-created_at'], name='recruitment_applica_b507dd_idx'), models.Index(fields=['status', '-created_at'], name='recruitment_status_99e876_idx')],
            },
        ),
    ]
