# Generated by Django 5.1.5 on 2026-08-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0016_consent_recorded_by_self'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='external_form_item_map',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
