# Generated by Django 5.1.5 on 2026-08-20 04:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0019_feedback_without_a_form'),
        ('workflows', '0003_recruiter_verification_and_screen_out'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatenotification',
            name='kind',
            field=models.CharField(choices=[('application_received', 'Application received'), ('hr_verification_passed', 'HR verification passed'), ('hr_verification_rejected', 'HR verification rejected'), ('interview_slot_invite', 'Interview slot selection'), ('interview_scheduled', 'Interview scheduled'), ('interview_rescheduled', 'Interview rescheduled'), ('interview_cancelled', 'Interview cancelled'), ('interview_selected', 'Selected for next round'), ('interview_not_selected', 'Not selected after interview'), ('interview_on_hold', 'Application under further review'), ('department_decision', 'Department decision'), ('final_selection', 'Final selection'), ('final_rejection', 'Final rejection'), ('offer_sent', 'Offer sent'), ('offer_accepted', 'Offer accepted'), ('offer_declined', 'Offer declined')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='InterviewSlotInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('token', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('options', models.JSONField(default=list)),
                ('selected_slot', models.JSONField(blank=True, default=dict)),
                ('selected_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', "Awaiting the candidate's choice"), ('selected', 'Slot chosen — awaiting HR confirmation'), ('confirmed', 'Interview scheduled'), ('expired', 'Expired unanswered'), ('cancelled', 'Withdrawn')], db_index=True, default='pending', max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_invites', to='recruitment.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_invites', to='recruitment.candidate')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slot_invites', to='workflows.workflowstage')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', 'status'], name='recruitment_applica_fe0922_idx')],
            },
        ),
    ]
