# Generated by Django 5.1.5 on 2026-08-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0020_slot_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='age_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='gender_preference',
            field=models.CharField(blank=True, choices=[('any', 'Any'), ('male', 'Male'), ('female', 'Female')], default='any', max_length=10),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='salary',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
