# Generated by Django 5.1.5 on 2026-08-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0021_jobopening_age_limit_jobopening_gender_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='calendar_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='calendar_event_id',
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
        migrations.AddField(
            model_name='interview',
            name='calendar_sync_status',
            field=models.CharField(blank=True, choices=[('', 'Not attempted'), ('synced', 'Synced'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='candidatenotification',
            name='kind',
            field=models.CharField(choices=[('application_received', 'Application received'), ('hr_verification_passed', 'HR verification passed'), ('hr_verification_rejected', 'HR verification rejected'), ('interview_slot_invite', 'Interview slot selection'), ('interview_rebooking', 'Interview time to be rebooked'), ('interview_scheduled', 'Interview scheduled'), ('interview_rescheduled', 'Interview rescheduled'), ('interview_cancelled', 'Interview cancelled'), ('interview_selected', 'Selected for next round'), ('interview_not_selected', 'Not selected after interview'), ('interview_on_hold', 'Application under further review'), ('department_decision', 'Department decision'), ('final_selection', 'Final selection'), ('final_rejection', 'Final rejection'), ('offer_sent', 'Offer sent'), ('offer_accepted', 'Offer accepted'), ('offer_declined', 'Offer declined')], db_index=True, max_length=40),
        ),
    ]
