# Generated by Django 5.1.5 on 2026-08-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0022_interview_calendar_error_interview_calendar_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='letter_pdf',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='offers/letters/'),
        ),
    ]
