# Generated by Django 5.1.5 on 2026-08-13 06:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_probationreview_employee_probation_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmailAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('email_address', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('provider', models.CharField(choices=[('google_workspace', 'Google Workspace'), ('microsoft_365', 'Microsoft 365'), ('zoho', 'Zoho Mail'), ('other', 'Other')], default='google_workspace', max_length=30)),
                ('external_account_id', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('provisioning', 'Being provisioned'), ('active', 'Active'), ('suspended', 'Suspended'), ('deprovisioned', 'Deprovisioned')], db_index=True, default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('deprovisioned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='email_account', to='employees.employee')),
                ('provisioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='itaccounts__status_24821b_idx')],
            },
        ),
    ]
