# Generated by Django 5.1.5 on 2026-09-09 06:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_documenttype_code_alter_employee_employee_code_and_more'),
        ('itaccounts', '0001_initial'),
        ('organization', '0002_remove_designation_uniq_designation_title_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemailaccount',
            name='email_address',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AddConstraint(
            model_name='companyemailaccount',
            constraint=models.UniqueConstraint(fields=('organization', 'email_address'), name='uniq_emailaccount_org_address'),
        ),
    ]
