# Generated by Django 5.1.5 on 2026-08-12 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HiringWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('department_kind', models.CharField(blank=True, choices=[('medical', 'Medical'), ('operations', 'Operations'), ('hr', 'Human Resources'), ('finance', 'Accounts & Finance'), ('other', 'Other')], help_text='Function this workflow serves. Blank = any.', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False, help_text='Only a published workflow may be attached to a job opening. Drafts can be edited freely; publishing freezes the shape.')),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('application', 'Application received'), ('hr_verification', 'HR verification'), ('interview', 'Interview'), ('department_decision', 'Department recommendation'), ('hr_final_decision', 'HR Head final decision'), ('offer', 'Offer'), ('onboarding', 'Onboarding'), ('terminal', 'Terminal')], max_length=30)),
                ('allowed_decisions', models.JSONField(default=list, help_text='Decision values this stage may record.')),
                ('requires_interview', models.BooleanField(default=False)),
                ('requires_feedback', models.BooleanField(default=False)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('can_skip', models.BooleanField(default=False)),
                ('is_final_hr_decision', models.BooleanField(default=False, help_text='This stage carries terminal SELECT/REJECT authority. Exactly one per workflow.')),
                ('is_terminal', models.BooleanField(default=False)),
                ('is_won', models.BooleanField(default=False)),
                ('sla_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('feedback_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='workflows.feedbackform')),
                ('responsible_role', models.ForeignKey(blank=True, help_text='Role permitted to act. Null for automatic stages.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_stages', to='accounts.role')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='workflows.hiringworkflow')),
            ],
            options={
                'ordering': ['workflow', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StageTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('on_decision', models.CharField(choices=[('pass', 'Pass — advance'), ('verify', 'Verified'), ('request_info', 'Request more information'), ('recommend_select', 'Recommend selection'), ('recommend_reject', 'Recommend rejection'), ('select', 'Select'), ('reject', 'Reject'), ('offer_accepted', 'Offer accepted'), ('offer_declined', 'Offer declined'), ('withdraw', 'Candidate withdrew')], max_length=30)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='workflows.workflowstage')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='workflows.workflowstage')),
            ],
            options={
                'ordering': ['from_stage__order'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('key', models.SlugField()),
                ('label', models.CharField(max_length=200)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('rating_1_5', 'Rating (1-5)'), ('text', 'Free text'), ('boolean', 'Yes / No'), ('choice', 'Single choice')], max_length=20)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='workflows.feedbackform')),
            ],
            options={
                'ordering': ['form', 'order'],
                'constraints': [models.UniqueConstraint(fields=('form', 'key'), name='uniq_field_key_per_form')],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.UniqueConstraint(fields=('workflow', 'order'), name='uniq_stage_order_per_workflow'),
        ),
        migrations.AddConstraint(
            model_name='stagetransition',
            constraint=models.UniqueConstraint(fields=('from_stage', 'on_decision'), name='uniq_transition_per_decision'),
        ),
    ]
