# Generated by Django 5.1.5 on 2026-08-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagetransition',
            name='on_decision',
            field=models.CharField(choices=[('pass', 'Pass — advance'), ('verify', 'Verified'), ('request_info', 'Request more information'), ('screen_out', 'Reject application'), ('recommend_select', 'Recommend selection'), ('recommend_reject', 'Recommend rejection'), ('select', 'Select'), ('reject', 'Reject'), ('offer_accepted', 'Offer accepted'), ('offer_declined', 'Offer declined'), ('withdraw', 'Candidate withdrew')], max_length=30),
        ),
    ]
