# Generated by Django 5.1.5 on 2026-09-09 06:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_designation_uniq_designation_title_department_and_more'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='name',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='hiringworkflow',
            name='name',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='feedbackform',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_feedbackform_org_name'),
        ),
        migrations.AddConstraint(
            model_name='hiringworkflow',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_hiringworkflow_org_name'),
        ),
    ]
