# Generated by Django 5.1.5 on 2026-08-17 07:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruitment', '0011_schedule_retention_purge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('platform', models.CharField(db_index=True, max_length=40)),
                ('original_filename', models.CharField(max_length=120)),
                ('file_sha256', models.CharField(db_index=True, max_length=64)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('declared_content_type', models.CharField(blank=True, max_length=100)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('parsed', 'Parsed — awaiting attestation'), ('committing', 'Committing'), ('completed', 'Completed'), ('partial', 'Completed with failures'), ('discarded', 'Discarded')], db_index=True, default='parsed', max_length=20)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_created', models.PositiveIntegerField(default=0)),
                ('rows_updated', models.PositiveIntegerField(default=0)),
                ('rows_duplicate', models.PositiveIntegerField(default=0)),
                ('rows_review', models.PositiveIntegerField(default=0)),
                ('rows_failed', models.PositiveIntegerField(default=0)),
                ('legal_basis', models.CharField(blank=True, max_length=32)),
                ('legal_basis_note', models.TextField(blank=True)),
                ('platform_account_ref', models.CharField(blank=True, max_length=120)),
                ('source_export_date', models.DateField(blank=True, null=True)),
                ('attestation_text', models.TextField(blank=True)),
                ('attested_at', models.DateTimeField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('attested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidate_import_attestations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_opening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='recruitment.jobopening')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('row_number', models.PositiveIntegerField()),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email_normalized', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone_e164', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('current_employer', models.CharField(blank=True, max_length=160)),
                ('total_experience_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('expected_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notice_period_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('row_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('needs_review', 'Needs review'), ('duplicate_in_file', 'Duplicate within the file'), ('created', 'Candidate created'), ('matched_updated', 'Existing candidate enriched'), ('matched_skipped', 'Existing candidate, nothing to add'), ('application_exists', 'Already applied to this job'), ('failed', 'Failed')], db_index=True, default='pending', max_length=24)),
                ('match_rule', models.CharField(blank=True, choices=[('external_id', 'Platform candidate ID'), ('email', 'Normalized email'), ('phone', 'Normalized phone'), ('none', 'No match — created')], max_length=16)),
                ('duplicate_of_row', models.PositiveIntegerField(blank=True, null=True)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.importbatch')),
                ('matched_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recruitment.candidate')),
            ],
            options={
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='imports_imp_uploade_144b30_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['job_opening', 'status'], name='imports_imp_job_ope_78d193_idx'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['committing', 'completed', 'partial']), _negated=True), models.Q(('attested_by__isnull', False), ('attested_at__isnull', False), models.Q(('legal_basis', ''), _negated=True), models.Q(('legal_basis_note', ''), _negated=True)), _connector='OR'), name='ck_import_committed_requires_attestation'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('legal_basis_note', ''), ('legal_basis_note__length__gte', 20), _connector='OR'), name='ck_import_basis_note_minimum_length'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['batch', 'status'], name='imports_imp_batch_i_4b8c02_idx'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['batch', 'row_fingerprint'], name='imports_imp_batch_i_438de8_idx'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='uniq_import_row_per_batch'),
        ),
    ]
