# Generated by Django 5.1.5 on 2026-09-08 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
        ('organization', '0001_initial'),
        ('recruitment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='job_opening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='recruitment.jobopening'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_imports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importrow',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.importbatch'),
        ),
        migrations.AddField(
            model_name='importrow',
            name='matched_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recruitment.candidate'),
        ),
        migrations.AddField(
            model_name='importrow',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.organization'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='imports_imp_uploade_144b30_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['job_opening', 'status'], name='imports_imp_job_ope_78d193_idx'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['committing', 'completed', 'partial']), _negated=True), models.Q(('attested_by__isnull', False), ('attested_at__isnull', False), models.Q(('legal_basis', ''), _negated=True), models.Q(('legal_basis_note', ''), _negated=True)), _connector='OR'), name='ck_import_committed_requires_attestation'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('legal_basis_note', ''), ('legal_basis_note__length__gte', 20), _connector='OR'), name='ck_import_basis_note_minimum_length'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['batch', 'status'], name='imports_imp_batch_i_4b8c02_idx'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['batch', 'row_fingerprint'], name='imports_imp_batch_i_438de8_idx'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='uniq_import_row_per_batch'),
        ),
    ]
