# Generated by Django 5.1.5 on 2026-09-19 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_photo'),
        ('imports', '0002_initial'),
        ('organization', '0005_orgemailtemplate'),
        ('recruitment', '0003_alter_candidate_resume_alter_offer_letter_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='importbatch',
            name='ck_import_committed_requires_attestation',
        ),
        migrations.AddField(
            model_name='importbatch',
            name='kind',
            field=models.CharField(choices=[('candidates', 'Candidates'), ('employees', 'Employees')], db_index=True, default='candidates', max_length=20),
        ),
        migrations.AddField(
            model_name='importrow',
            name='created_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='job_opening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='recruitment.jobopening'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'employees'), models.Q(('status__in', ['committing', 'completed', 'partial']), _negated=True), models.Q(('attested_by__isnull', False), ('attested_at__isnull', False), models.Q(('legal_basis', ''), _negated=True), models.Q(('legal_basis_note', ''), _negated=True)), _connector='OR'), name='ck_import_committed_requires_attestation'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('job_opening__isnull', False), ('kind', 'candidates')), models.Q(('job_opening__isnull', True), ('kind', 'employees')), _connector='OR'), name='ck_import_job_matches_kind'),
        ),
    ]
