# Generated by Django 5.1.5 on 2026-08-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_schedule_staging_purge'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='detected_headers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='unmapped_headers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
