"""
Prove tenant isolation against a running system, and write down what happened.

    cd apps/api
    python manage.py shell -c "exec(open('../../scripts/verify_tenant_isolation.py').read())"

Not `shell < script`. With IPython installed, Django's shell reads a redirected
file as if somebody were typing it, and a blank line inside an indented block
ends the block -- so the loops below silently do not run and the script reports
zero checks and zero failures, which is the most dangerous output it could
possibly produce. `exec()` compiles the whole file at once.

Three organizations are provisioned, populated with fictional HR data, and then
every one of them is told to go and fetch the others' records -- as its own
Admin, who holds Scope.ALL almost everywhere and is therefore the principal
with the most reach to override. Every attempt must be refused.

The output is `TENANT_ISOLATION_TEST_REPORT.md` at the repository root, written
from the results rather than from a description of them. That is the whole
point of the script: the brief asks not to be told the system is multi-tenant
but to be shown, and a document generated by the attempts themselves cannot
claim an attempt that was never made.

WHAT COUNTS AS A REFUSAL
------------------------
404, not 403. A 403 says "this exists and you may not have it", which tells
one customer that a record of another exists -- so the requirement is that
another organization's row is indistinguishable from a row that was never
there. The script records the distinction and reports 403s separately rather
than counting them as passes.

WHY EACH REFUSAL IS PAIRED WITH A POSITIVE CONTROL
--------------------------------------------------
A route that refuses everybody proves nothing about tenancy. Every cross-org
attempt below is preceded by the same request against the caller's OWN
equivalent row, and an attempt whose control did not succeed is reported as
INCONCLUSIVE rather than as a pass. Without that, a typo in a URL reads as
perfect isolation.

NO REAL DATA
------------
Every name, address and email here is invented, every domain is `.example`
(reserved by RFC 2606 and unroutable), and passwords are generated per run and
never written down -- not to a file, not to this source, not to the report.
"""

import datetime as dt
import secrets
import sys
from collections import Counter
from contextlib import contextmanager as _contextmanager
from decimal import Decimal
from pathlib import Path

from django.conf import settings
from django.utils import timezone
from rest_framework.test import APIClient

from core.access.routewalk import concretize, detail_routes, model_of, rows_for
from core.middleware import acting_as


@_contextmanager
def across_organizations():
    """
    The god's-eye view, for this report's OWN verification.

    RELEASE 2. The application now connects as `generic_hrms_app`, which the
    database confines to the bound organization. That is the property this
    report exists to demonstrate -- and it is also why the report can no
    longer read the world freely to check its own work. "Both rows still
    exist", "the creation was audited", "the other organization's employee did
    not change": each of those is a statement ABOUT the database, not a thing
    the product does, and each now goes through the same named door the
    platform uses.

    Never wrap a PROBE in this. The probes -- the API calls, the manager
    reads, the route walk -- must stay confined, or the report would be
    proving nothing at all.
    """
    from django.db import transaction

    from core.access.platform_bypass import platform_bypass

    with transaction.atomic(), platform_bypass(
        reason="isolation report: verify what is really in the database", system=True
    ):
        yield


sys.stdout.reconfigure(encoding="utf-8")

#: Unique per run, so the script is re-runnable against the same database
#: without colliding with the organizations it made last time.
NONCE = secrets.token_hex(3)

RESULTS = []


def check(name, ok, detail="", *, inconclusive=False):
    status = "SKIP" if inconclusive else ("PASS" if ok else "FAIL")
    RESULTS.append((name, status, str(detail)[:300]))
    line = f"{status} {name}"
    if status != "PASS" and detail:
        line += f"  :: {str(detail)[:200]}"
    print(line)
    return ok


# ---------------------------------------------------------------------------
# 1. Three organizations, sized as the brief asks
# ---------------------------------------------------------------------------

#: (slug, display name, employees, departments, locations). The sizes are the
#: brief's. The industries are the brief's too, and they matter beyond
#: flavour: three different shapes of company is what stops the proof being
#: "two copies of the same fixture agree with each other".
PROFILES = [
    ("healthcare", "Northwind Health", 20, 5, 3),
    ("technology", "Aperture Systems", 15, 4, 2),
    ("retail", "Fairhaven Retail", 10, 3, 2),
]

DEPARTMENT_NAMES = ["People", "Finance", "Operations", "Technology", "Support"]
CITIES = [("Pune", "MH"), ("Bengaluru", "KA"), ("Jaipur", "RJ")]
FIRST_NAMES = [
    "Aditi", "Bhavna", "Chetan", "Devika", "Esha", "Farhan", "Gaurav", "Hema",
    "Imran", "Jaya", "Kabir", "Leela", "Manav", "Nisha", "Omkar", "Preeti",
    "Rahul", "Sanya", "Tarun", "Uma",
]
LAST_NAMES = ["Rao", "Menon", "Iyer", "Bose", "Kulkarni", "Nair", "Verma", "Sen"]


def full_plan():
    """
    The plan the report's organizations are sold: one that disables NOTHING.

    Provisioning without a plan puts a customer on the cheapest public one,
    and on a deployment that sells Starter that switches payroll and reporting
    off. Every payroll and dashboard probe then answers `feature_not_available`
    for the caller's own row as well as the victim's -- so it is reported as
    inconclusive at best, and the report quietly stops covering two modules.
    That is what happened the first time this script ran through the service.

    A deployment that sells nothing has no plans; then there is no
    subscription and every module is on, which is what `None` gives. A
    deployment whose plans ALL disable something cannot host a full proof, and
    is told so rather than handed a report that covers less than it claims.
    """
    from apps.platform.models import Plan

    plans = list(Plan.objects.filter(is_active=True).order_by("display_order", "code"))
    if not plans:
        return None
    for plan in plans:
        if not plan.disabled_features:
            return plan
    raise SystemExit(
        "Every active plan disables at least one module, so no organization "
        "here can be provisioned with everything switched on, and a report "
        "covering fewer modules than it names would be worse than none. Create "
        "or reactivate a plan with no disabled features (seed_plans ships "
        "'enterprise')."
    )


FULL_PLAN = full_plan()


def _creation_was_audited(org) -> bool:
    """Did provisioning write the creation into the organization's own trail?"""
    from apps.audit.models import AuditLog

    with across_organizations():
        return AuditLog.objects.filter(
            organization=org,
            entity_type="organization.Organization",
            action="create",
        ).exists()


def provision(slug_base, name, n_employees, n_departments, n_locations):
    """
    One complete organization with its own everything.

    CREATED BY THE PLATFORM PROVISIONING SERVICE, the same atomic call the
    console makes for a real customer: organization, settings, configuration
    seeds, first administrator with membership and Admin grant, audit row,
    invitation. It used to be built here by hand -- `Organization.objects.
    create`, `seed_roles`, a hand-made admin -- which meant 295 checks proved
    isolation between organizations that no real customer would ever resemble,
    created by a path no real customer goes through. An isolation defect in
    anything provisioning seeds (leave types, document types, shift rules,
    hiring workflows, letter templates) was invisible to this report.

    What stays hand-built is the DATA: departments, people, a payroll run, a
    candidate. Those are the rows the walk needs to aim at, and a customer
    creates them through the application after provisioning, exactly as here.

    The organization then goes live through `finish_setup`, whose refusal on
    an incomplete company makes reaching an operational status an assertion
    in its own right.
    """
    from django.core import mail
    from django.test.utils import override_settings

    from apps.accounts.models import Role, User, UserRole
    from apps.audit.models import AuditLog
    from apps.organization.setup import finish_setup
    from apps.platform.services.provisioning import provision_organization
    from apps.assets.models import Asset, AssetCategory
    from apps.attendance.models import AttendanceRecord
    from apps.employees.models import Employee
    from apps.leave.models import LeaveRequest, LeaveType
    from apps.organization.models import (
        Department,
        Designation,
        EmployeeLevel,
        Location,
        OrganizationMembership,
    )
    from apps.payroll.models import PayrollRun
    from apps.recruitment.models import Candidate
    from core.access.catalog import DepartmentKind, Layer

    # Imported from the test tree ON PURPOSE, and it is worth saying why. Both
    # this script and `tests/tenancy/test_route_walker.py` need the same thing:
    # an organization populated broadly enough that the route walk can ask
    # about payroll, recruitment, offboarding and the rest rather than about
    # departments six times. Two definitions of that would drift, and the one
    # that drifted would be this one -- the proof, not the gate, because the
    # gate runs on every commit and this does not. Sharing one builder means
    # the report cannot quietly cover less than the suite does.
    from tests.tenancy._extra import build_extra_rows

    slug = f"{slug_base}-{NONCE}"
    domain = f"{slug}.example"

    # The invitation goes to an in-memory outbox, whatever this deployment's
    # mail settings say. Provisioning sends it on commit, and a report run
    # against a server with real SMTP must never mail anybody -- `.example`
    # cannot resolve, but a bounce is still mail leaving the building. The
    # outbox also lets the report ASSERT the invitation was attempted, which is
    # the last step of the provisioning path and the one most easily skipped.
    with override_settings(EMAIL_BACKEND="django.core.mail.backends.locmem.EmailBackend"):
        mail.outbox = []
        provisioned = provision_organization(
            name=name,
            legal_name=f"{name} Private Limited",
            slug=slug,
            admin_email=f"admin@{domain}",
            admin_first_name="Admin",
            admin_last_name=name.split()[0],
            plan=FULL_PLAN,
        )
        invitations = [m for m in mail.outbox if f"admin@{domain}" in m.to]
    org = provisioned.organization

    world = {"organization": org, "name": name, "slug": slug, "domain": domain,
             "passwords": {}, "rows": {},
             "seeded": sorted(provisioned.seeded),
             "plan": FULL_PLAN.code if FULL_PLAN else "none (every module on)",
             "invitations": len(invitations),
             "audited": _creation_was_audited(org)}

    # The provisioned administrator arrives with a temporary password and
    # `must_change_password`, which the API enforces on every request. That
    # gate has its own tests; this report is about tenancy, so the
    # administrator is given a password of this run's choosing -- generated,
    # never written down -- the way a real one would after first sign-in.
    admin = provisioned.admin
    admin_password = secrets.token_urlsafe(18)
    admin.set_password(admin_password)
    admin.must_change_password = False
    admin.save(update_fields=["password", "must_change_password"])
    world["passwords"][admin.email] = admin_password

    with acting_as(None, organization=org):
        roles = {r.code: r for r in Role.objects.filter(organization=org)}

        locations = [
            Location.objects.create(
                name=f"{name} {CITIES[i][0]}", code=f"L{i + 1}",
                city=CITIES[i][0], state=CITIES[i][1], is_head_office=(i == 0),
            )
            for i in range(n_locations)
        ]
        departments = [
            Department.objects.create(
                name=DEPARTMENT_NAMES[i], code=f"D{i + 1}",
                kind=DepartmentKind.HR if i == 0 else DepartmentKind.OPERATIONS,
            )
            for i in range(n_departments)
        ]
        level = EmployeeLevel.objects.create(name="Staff", code="L5", layer=Layer.STAFF)
        designation = Designation.objects.create(title="Officer", department=None)

        def make_user(role_code, local):
            password = secrets.token_urlsafe(18)
            user = User.objects.create_user(
                email=f"{local}@{domain}", password=password,
                first_name=role_code.replace("_", " ").title(), last_name=name.split()[0],
            )
            UserRole.objects.create(user=user, role=roles[role_code])
            OrganizationMembership.objects.create(organization=org, user=user)
            world["passwords"][user.email] = password
            return user

        hr = make_user("hr_head", "hr")
        worker = make_user("employee", "employee")

        employees = []
        for i in range(n_employees):
            linked = {0: hr, 1: worker}.get(i)
            employees.append(
                Employee.objects.create(
                    employee_code=f"EMP{i + 1:03d}",
                    user=linked,
                    first_name=FIRST_NAMES[i % len(FIRST_NAMES)],
                    last_name=LAST_NAMES[i % len(LAST_NAMES)],
                    department=departments[i % n_departments],
                    designation=designation,
                    location=locations[i % n_locations],
                    level=level,
                    date_of_joining=dt.date(2024, 1, 1),
                )
            )

        subject = employees[1]
        # No user and no role: the offboarding rows hang off this one, so the
        # employee the rest of the checks use is not simultaneously resigning.
        spare = Employee.objects.create(
            employee_code=f"EMP{n_employees + 1:03d}",
            first_name="Spare", last_name=name.split()[0],
            department=departments[0], designation=designation,
            location=locations[0], level=level,
            date_of_joining=dt.date(2024, 1, 1),
        )
        leave_type = LeaveType.objects.create(name="Casual Leave", code="CL")

        world["admin"], world["hr"], world["worker"] = admin, hr, worker
        world["employees"] = employees
        world["departments"] = departments
        world["locations"] = locations
        world["rows"] = {
            "employee": subject,
            "department": departments[0],
            "location": locations[0],
            "leave_type": leave_type,
            "leave_request": LeaveRequest.objects.create(
                employee=subject, leave_type=leave_type,
                start_date=dt.date(2025, 6, 2), end_date=dt.date(2025, 6, 2),
                days=Decimal("1.0"), reason="Isolation fixture",
            ),
            "attendance_record": AttendanceRecord.objects.create(
                employee=subject, date=dt.date(2025, 6, 3)
            ),
            "payroll_run": PayrollRun.objects.create(
                period_year=2025, period_month=6, run_by=hr
            ),
            "candidate": Candidate.objects.create(
                first_name="Ira", last_name="Dutta",
                email=f"applicant@{domain}", consent_given=True,
            ),
            # `employee_document` and `document_type` come from the shared
            # builder below, which already creates both -- creating them here
            # too collided on the per-organization uniqueness of the code.
            "asset": Asset.objects.create(
                asset_tag="AST-001",
                category=AssetCategory.objects.create(name="Laptops", code="LAPTOP"),
                name="ThinkPad",
            ),
        }

        # The rest of the product -- offboarding, onboarding, hiring workflows,
        # recruitment, payroll detail, devices, imports, audit. Without these
        # the walk below asks about nine kinds of object and stays silent about
        # everything else, which is not what this report should be claiming.
        world["rows"].update(
            build_extra_rows(
                organization=org,
                slug=slug,
                roles=roles,
                department=departments[0],
                location=locations[0],
                designation=designation,
                level=level,
                hr=hr,
                hr_employee=employees[0],
                worker_employee=subject,
                spare_employee=spare,
                leave_type=leave_type,
                asset=world["rows"]["asset"],
                candidate=world["rows"]["candidate"],
                payroll_run=world["rows"]["payroll_run"],
            )
        )

    # Live, through the wizard's own gate. It refuses while a required step
    # is outstanding and names which, so a failure here is a sentence about
    # what this builder forgot rather than a status quietly left pending.
    finish_setup(org)
    org.refresh_from_db()
    world["status"] = org.status
    return world


print("=" * 72)
print("Provisioning three organizations")
print("=" * 72)

WORLDS = [provision(*profile) for profile in PROFILES]

from apps.organization.models import OPERATIONAL_STATUSES  # noqa: E402
from apps.platform.services.provisioning import CONFIG_SEEDS  # noqa: E402

for w in WORLDS:
    check(
        f"1. {w['name']} provisioned ({len(w['employees'])} employees, "
        f"{len(w['departments'])} departments, {len(w['locations'])} locations)",
        len(w["employees"]) > 0 and len(w["rows"]) >= 9,
    )
    # That it came through the SERVICE, and all of it. Each is something a
    # hand-built organization would not have, so these fail if the seam above
    # is ever quietly reverted to ORM calls.
    expected_seeds = sorted(key for key, _what, _seed in CONFIG_SEEDS)
    check(
        f"1. {w['name']} carries every configuration seed provisioning applies",
        w["seeded"] == expected_seeds,
        f"seeded {w['seeded']}, expected {expected_seeds}",
    )
    check(
        f"1. {w['name']}'s creation is in its own audit trail",
        w["audited"],
    )
    check(
        f"1. {w['name']} is on a plan that disables nothing ({w['plan']})",
        FULL_PLAN is None or not FULL_PLAN.disabled_features,
    )
    check(
        f"1. {w['name']}'s administrator invitation was attempted (in-memory outbox)",
        w["invitations"] == 1,
        f"{w['invitations']} invitation(s)",
    )
    check(
        f"1. {w['name']} went live through finish_setup ({w['status']})",
        w["status"] in OPERATIONAL_STATUSES and w["status"] != "pending_setup",
        w["status"],
    )


#: Routes that raised instead of answering. An exception is not a refusal --
#: it is a bug -- so these are counted and reported separately rather than
#: quietly folded into either column.
ERRORED = []


def get(client, path):
    """
    A GET that returns a status instead of raising.

    The walk touches every detail route in the product. One view raising --
    a missing file on disk, a serializer that cannot render a half-built row --
    would otherwise abort the run and produce no report at all, which is the
    one outcome worse than a failing report.
    """
    try:
        return client.get(path).status_code
    except Exception as exc:  # noqa: BLE001 -- deliberately broad; see docstring
        ERRORED.append(f"{path} :: {type(exc).__name__}: {exc}")
        return None


def login(world, who):
    user = world[who]
    client = APIClient(HTTP_HOST="localhost")
    response = client.post(
        "/api/v1/auth/login/",
        {"email": user.email, "password": world["passwords"][user.email]},
        format="json",
    )
    if response.status_code != 200:
        return None
    client.credentials(HTTP_AUTHORIZATION="Bearer " + response.json()["access"])
    return client


CLIENTS = {}
for w in WORLDS:
    for who in ("admin", "hr", "worker"):
        client = login(w, who)
        CLIENTS[(w["slug"], who)] = client
        check(f"2. {w['name']} / {who} signs in", client is not None)


# ---------------------------------------------------------------------------
# 3. Each principal resolves to its OWN organization
# ---------------------------------------------------------------------------

for w in WORLDS:
    client = CLIENTS[(w["slug"], "admin")]
    if client is None:
        check(f"3. {w['name']} admin resolves to its own organization", False,
              "could not sign in")
        continue
    branding = client.get("/api/v1/org/branding/?org=" + w["slug"])
    check(
        f"3. {w['name']} admin's own organization answers",
        branding.status_code == 200 and branding.json().get("name") == w["name"],
        branding.content[:160],
    )


# ---------------------------------------------------------------------------
# 4. Lists contain the caller's rows and nobody else's
# ---------------------------------------------------------------------------

LIST_ROUTES = {
    "employees": "/api/v1/employees/",
    "departments": "/api/v1/departments/",
    "locations": "/api/v1/locations/",
    "leave requests": "/api/v1/leave-requests/",
    "attendance": "/api/v1/attendance-records/",
    "payroll runs": "/api/v1/payroll/runs/",
    "candidates": "/api/v1/candidates/",
    "documents": "/api/v1/employee-documents/",
    "audit logs": "/api/v1/audit/",
}


def ids_in(payload):
    rows = payload.get("data", payload) if isinstance(payload, dict) else payload
    if not isinstance(rows, list):
        return set()
    return {str(r.get("id")) for r in rows if isinstance(r, dict) and "id" in r}


print()
print("=" * 72)
print("Cross-organization list reads")
print("=" * 72)

LIST_FINDINGS = []
for w in WORLDS:
    client = CLIENTS[(w["slug"], "admin")]
    others = [o for o in WORLDS if o is not w]
    for label, path in LIST_ROUTES.items():
        response = client.get(path)
        if response.status_code != 200:
            check(f"4. {w['name']} lists {label}", False, response.status_code,
                  inconclusive=True)
            continue
        seen = ids_in(response.json())
        foreign = set()
        for other in others:
            for row in other["rows"].values():
                if str(row.pk) in seen:
                    foreign.add(f"{other['name']}:{row.pk}")
            for employee in other["employees"]:
                if str(employee.pk) in seen:
                    foreign.add(f"{other['name']}:{employee.pk}")
        if foreign:
            LIST_FINDINGS.append((w["name"], label, sorted(foreign)))
        check(f"4. {w['name']}'s {label} list contains no other organization's rows",
              not foreign, sorted(foreign))


# ---------------------------------------------------------------------------
# 5. Detail reads of a named row belonging to somebody else
# ---------------------------------------------------------------------------

DETAIL_ROUTES = {
    "employee": "/api/v1/employees/{}/",
    "department": "/api/v1/departments/{}/",
    "location": "/api/v1/locations/{}/",
    "leave_request": "/api/v1/leave-requests/{}/",
    "attendance_record": "/api/v1/attendance-records/{}/",
    "payroll_run": "/api/v1/payroll/runs/{}/",
    "candidate": "/api/v1/candidates/{}/",
    "employee_document": "/api/v1/employee-documents/{}/",
    "leave_type": "/api/v1/leave-types/{}/",
}

print()
print("=" * 72)
print("Cross-organization detail reads")
print("=" * 72)

STATUS_TALLY = Counter()
LEAKS = []
DISCLOSED_BY_403 = []

for w in WORLDS:
    client = CLIENTS[(w["slug"], "admin")]
    for other in WORLDS:
        if other is w:
            continue
        for key, template in DETAIL_ROUTES.items():
            # The positive control, first and every time: the SAME route
            # against this caller's own row. A refusal below means nothing
            # unless this succeeded.
            control = get(client, template.format(w["rows"][key].pk))
            attempt = get(client, template.format(other["rows"][key].pk))
            STATUS_TALLY[attempt] += 1
            name = (f"5. {w['name']} reading {other['name']}'s {key}")
            if control != 200:
                check(name, False, f"control returned {control}", inconclusive=True)
                continue
            if attempt == 200:
                LEAKS.append((w["name"], other["name"], key, attempt))
                check(name, False, "SERVED IT (200)")
            elif attempt == 403:
                DISCLOSED_BY_403.append((w["name"], other["name"], key))
                check(name, False, "403 confirms the row exists; 404 required")
            else:
                check(name, attempt == 404, attempt)


# ---------------------------------------------------------------------------
# 6. Writes: neither editing another organization's row nor borrowing its ids
# ---------------------------------------------------------------------------

print()
print("=" * 72)
print("Cross-organization writes")
print("=" * 72)

for w in WORLDS:
    client = CLIENTS[(w["slug"], "admin")]
    for other in WORLDS:
        if other is w:
            continue

        patch = client.patch(
            f"/api/v1/employees/{other['rows']['employee'].pk}/",
            {"phone": "9000000000"}, format="json",
        )
        check(
            f"6. {w['name']} cannot edit {other['name']}'s employee",
            patch.status_code == 404, patch.status_code,
        )

        # The injection vector: a well-formed create naming ANOTHER
        # organization's department. Refusing this is what stops a valid
        # request from quietly stitching two tenants together.
        #
        # The payload must be valid in EVERY other respect. An earlier version
        # of this check sent `department` instead of `department_id` and left
        # out `email` and `role_code`, so every run was refused for the missing
        # fields and reported PASS without the department ever being looked at.
        # Refused-for-the-right-reason is asserted below, and a positive control
        # with the caller's own department makes an incomplete payload show up
        # as INCONCLUSIVE instead of as isolation.
        def _employee_payload(world, department_pk, tag):
            token = secrets.token_hex(3)
            return {
                "first_name": "Injected", "last_name": f"Row{tag}",
                "email": f"injected-{tag}-{token}@{world['domain']}",
                "personal_email": f"injected-{tag}-{token}.personal@{world['domain']}",
                "role_code": "employee",
                "department_id": str(department_pk),
                "designation_id": str(world["rows"]["employee"].designation_id),
                "location_id": str(world["rows"]["location"].pk),
                "level_id": str(world["rows"]["employee"].level_id),
                "reporting_manager_id": str(world["rows"]["employee"].pk),
                "date_of_joining": "2025-01-01",
            }

        control = client.post(
            "/api/v1/employees/",
            _employee_payload(w, w["rows"]["department"].pk, "own"),
            format="json",
        )
        created = client.post(
            "/api/v1/employees/",
            _employee_payload(w, other["rows"]["department"].pk, "foreign"),
            format="json",
        )
        body = created.content.decode(errors="replace").lower()
        check(
            f"6b. {w['name']} cannot create an employee in {other['name']}'s department",
            created.status_code == 400 and "department" in body,
            f"{created.status_code} {created.content[:140]}",
            inconclusive=control.status_code != 201,
        )

        # Relation ids in the body of a CUSTOM endpoint. This is the vector the
        # checks above never tried, and it was open: a declared
        # `PrimaryKeyRelatedField` on a plain Serializer resolved any
        # organization's employee, and `POST /exits/` then offboarded them --
        # status set to resigned, login and mailbox flagged, a settlement
        # created. The victim's state is re-read from the database, because a
        # 400 that still changed the row would not be a refusal.
        import datetime as _dt

        from apps.employees.models import Employee as _Employee
        from apps.offboarding.models import ExitWorkflow as _ExitWorkflow

        victim = other["rows"]["employee"]
        # A different employee of the caller's for each other organization. The
        # control files a real resignation, and a second one for the same person
        # is refused as already awaiting review -- which read as INCONCLUSIVE on
        # every second pass through this loop.
        other_index = next(i for i, candidate in enumerate(WORLDS) if candidate is other)
        own_subject = w["employees"][-1 - other_index]
        in_thirty_days = str(_dt.date.today() + _dt.timedelta(days=30))
        exit_type = _ExitWorkflow._meta.get_field("exit_type").choices[0][0]

        def _victim_state(victim_pk):
            # The OTHER organization's row, read as the platform: the point is
            # to show the probe below left it untouched.
            with across_organizations():
                row = _Employee.objects.all_orgs().get(pk=victim_pk)
            return (row.status, row.is_active)

        before = _victim_state(victim.pk)
        foreign_exit = client.post(
            "/api/v1/exits/",
            {"employee": str(victim.pk), "exit_type": exit_type,
             "last_working_date": in_thirty_days},
            format="json",
        )
        check(
            f"6c. {w['name']} cannot offboard {other['name']}'s employee",
            foreign_exit.status_code in (400, 404)
            and "employee" in foreign_exit.content.decode(errors="replace").lower()
            and _victim_state(victim.pk) == before,
            f"{foreign_exit.status_code} {foreign_exit.content[:140]}",
        )

        foreign_resignation = client.post(
            "/api/v1/resignations/",
            {"employee": str(victim.pk),
             "requested_last_working_date": in_thirty_days, "reason": "probe"},
            format="json",
        )
        own_resignation = client.post(
            "/api/v1/resignations/",
            {"employee": str(own_subject.pk),
             "requested_last_working_date": in_thirty_days, "reason": "control"},
            format="json",
        )
        check(
            f"6d. {w['name']} cannot file a resignation for {other['name']}'s employee",
            foreign_resignation.status_code in (400, 404)
            and "employee" in foreign_resignation.content.decode(errors="replace").lower()
            and _victim_state(victim.pk) == before,
            f"{foreign_resignation.status_code} {foreign_resignation.content[:140]}",
            inconclusive=own_resignation.status_code != 201,
        )


# ---------------------------------------------------------------------------
# 7. The whole detail surface, not the nine routes chosen above
# ---------------------------------------------------------------------------

print()
print("=" * 72)
print("Full route walk")
print("=" * 72)

EXCLUDED = ("/api/v1/auth/", "/api/v1/bootstrap/")

ROUTES_TOTAL = len(detail_routes())


def walk(caller, victim):
    """Every detail route the caller can answer, asked for the victim's row."""
    client = CLIENTS[(caller["slug"], "admin")]
    served, refused, leaked = 0, 0, []
    for template, view in detail_routes():
        if "pk" not in template:
            continue
        model = model_of(view)
        if model is None or not hasattr(model, "organization_id"):
            continue
        # Choosing WHICH rows to aim at is the harness's own reach, not the
        # product's -- the requests below are ordinary confined ones, and they
        # are what the check is about.
        with across_organizations():
            mine = rows_for(model, caller["organization"].pk).first()
            theirs = rows_for(model, victim["organization"].pk).first()
        if mine is None or theirs is None:
            continue
        my_path = concretize(template, mine.pk)
        their_path = concretize(template, theirs.pk)
        if not my_path or not their_path or my_path.startswith(EXCLUDED):
            continue
        # Only routes that answer for the caller's OWN row can distinguish a
        # tenancy refusal from a route that refuses everyone.
        if get(client, my_path) != 200:
            continue
        served += 1
        status = get(client, their_path)
        if status in (403, 404, 405):
            refused += 1
        elif status is None:
            pass  # raised rather than answered; counted in ERRORED, not here
        else:
            leaked.append(f"{status} {their_path} ({view.__name__} -> {model._meta.label})")
    return served, refused, leaked


WALK = []
for w in WORLDS:
    for other in WORLDS:
        if other is w:
            continue
        served, refused, leaked = walk(w, other)
        WALK.append((w["name"], other["name"], served, refused, leaked))
        check(
            f"7. {w['name']} -> {other['name']}: {refused}/{served} detail routes refused",
            not leaked and served > 0,
            leaked or "no route served the caller's own row",
        )


# ---------------------------------------------------------------------------
# 8. A non-admin has no wider reach than the admin who was already refused
# ---------------------------------------------------------------------------

print()
print("=" * 72)
print("Lesser principals")
print("=" * 72)

for w in WORLDS:
    for who in ("hr", "worker"):
        client = CLIENTS[(w["slug"], who)]
        for other in WORLDS:
            if other is w:
                continue
            status = get(client, f"/api/v1/employees/{other['rows']['employee'].pk}/")
            check(
                f"8. {w['name']} / {who} cannot read {other['name']}'s employee",
                status in (403, 404), status,
            )


# ---------------------------------------------------------------------------
# 9. Every organization-owned model filters at the manager, and fails closed
# ---------------------------------------------------------------------------
#
# Sections 1-8 are the HTTP surface. This one is underneath it: the layer that
# covers what a view mixin cannot, because two thirds of this codebase's
# queryset call sites are in services reached from commands and Celery as well
# as from requests. Asked per model rather than once, because "the mechanism
# exists" and "the mechanism is attached to this table" are different claims --
# and the first was true for a whole stage while the second was false of every
# table in the product.

print()
print("=" * 72)
print("Manager coverage")
print("=" * 72)

from django.apps import apps as django_apps  # noqa: E402

from core.access.checks import unfiltered_managers  # noqa: E402
from core.models import (  # noqa: E402
    OrgContextMissing,
    OrgOwnedModel,
    OrgOwnedTimestampedModel,
)

ORG_OWNED = [
    model
    for model in django_apps.get_models()
    if issubclass(model, OrgOwnedModel | OrgOwnedTimestampedModel)
]
MANAGER_APPS = sorted({m._meta.app_label for m in ORG_OWNED})

check(
    f"9. the app registry offers {len(ORG_OWNED)} organization-owned models "
    f"across {len(MANAGER_APPS)} apps",
    len(ORG_OWNED) >= 90,
    len(ORG_OWNED),
)

for model in sorted(ORG_OWNED, key=lambda m: m._meta.label):
    label = model._meta.label
    unfiltered = unfiltered_managers(model)

    with acting_as(None, organization=None):
        try:
            model.objects.all()
            refused_unbound, why = False, "returned a queryset with nothing bound"
        except OrgContextMissing:
            refused_unbound, why = True, ""
        except Exception as exc:  # noqa: BLE001
            refused_unbound, why = False, f"{type(exc).__name__}: {exc}"

        try:
            list(model.objects.all_orgs()[:1])
            hatch, hatch_why = True, ""
        except Exception as exc:  # noqa: BLE001
            hatch, hatch_why = False, f"all_orgs(): {type(exc).__name__}: {exc}"

    check(
        f"9. {label} filters, refuses an unbound read, and keeps all_orgs()",
        not unfiltered and refused_unbound and hatch,
        "; ".join(p for p in (", ".join(unfiltered), why, hatch_why) if p),
    )


# ---------------------------------------------------------------------------
# 10. Scheduled work runs for one organization, or it fails
# ---------------------------------------------------------------------------
#
# Every per-organization subtask the product ships, run for one of the three
# organizations while the other two are watched. The dispatchers themselves are
# NOT invoked: `fan_out` queues for every running organization on the
# deployment, which on a development database means somebody else's demo data.
# The subtask is where the tenancy lives anyway.

print()
print("=" * 72)
print("Scheduled work")
print("=" * 72)

import uuid as _uuid  # noqa: E402

from apps.attendance.tasks import sync_essl_for_organization  # noqa: E402
from apps.imports.tasks import purge_staging_pii_for_organization  # noqa: E402
from apps.leave.tasks import (  # noqa: E402
    convert_short_leave_for_organization,
    flag_absences_for_organization,
    monthly_accrual_for_organization,
)
from apps.recruitment.tasks import (  # noqa: E402
    purge_expired_candidates_for_organization,
    sync_google_form_responses_for_job,
    sync_google_form_responses_for_organization,
)
from apps.reporting.tasks import refresh_snapshots_for_organization  # noqa: E402
from core.tasks import UnknownOrganization  # noqa: E402

#: `apply=False` where the task destroys data. A dry run still exercises the
#: selection, which is the part that could reach across a boundary; the
#: destructive path is proved separately in section 12, against rows this
#: script created.
SUBTASKS = [
    ("attendance.sync_essl", sync_essl_for_organization, {}),
    ("leave.monthly_accrual", monthly_accrual_for_organization, {}),
    ("leave.convert_short_leave", convert_short_leave_for_organization, {}),
    ("leave.flag_absences", flag_absences_for_organization, {}),
    ("imports.purge_staging_pii", purge_staging_pii_for_organization, {"apply": False}),
    ("reporting.refresh_snapshots", refresh_snapshots_for_organization, {}),
    (
        "recruitment.purge_expired_candidates",
        purge_expired_candidates_for_organization,
        {"apply": False},
    ),
    (
        "recruitment.sync_google_form_responses",
        sync_google_form_responses_for_organization,
        {},
    ),
]


def _watched_state(worlds):
    """Rows whose change would mean a task reached into another organization."""
    from apps.employees.models import Employee
    from apps.recruitment.models import Candidate

    state = {}
    # A snapshot of OTHER organizations, taken to prove a task did not touch
    # them: the report's own bookkeeping, read as the platform.
    with across_organizations():
        for world in worlds:
            org = world["organization"]
            state[world["slug"]] = {
                "employees": sorted(
                    Employee.objects.all_orgs()
                    .filter(organization=org)
                    .values_list("pk", "first_name", "is_active", "updated_at")
                ),
                "candidates": sorted(
                    Candidate.objects.all_orgs()
                    .filter(organization=org)
                    .values_list("pk", "first_name", "email")
                ),
            }
    return state


for name, task, kwargs in SUBTASKS:
    for w in WORLDS:
        others = [o for o in WORLDS if o is not w]
        before = _watched_state(others)
        try:
            task(w["organization"].pk, **kwargs)
            ran, failure = True, ""
        except Exception as exc:  # noqa: BLE001
            ran, failure = False, f"{type(exc).__name__}: {exc}"
        after = _watched_state(others)
        check(
            f"10. {name} for {w['name']} changes no other organization's rows",
            ran and after == before,
            failure or "rows changed in another organization",
        )

    # An id that does not resolve is a fault, not an empty day's work. A task
    # that returned quietly here would make a tenant that stopped being
    # processed look exactly like a tenant with nothing to process.
    try:
        task(_uuid.uuid4(), **kwargs)
        refused = False
    except UnknownOrganization:
        refused = True
    except Exception as exc:  # noqa: BLE001
        refused = False
        check(f"10. {name} refuses an unknown organization", False, f"{type(exc).__name__}: {exc}")
        continue
    check(f"10. {name} refuses an unknown organization", refused)

# THE CASE THAT MATTERS: a task bound to one tenant, handed another's object
# id. It must RAISE. Silently finding nothing is indistinguishable from having
# no work to do, which is how a customer stops being processed for a month with
# nothing in any log.
from apps.recruitment.models import JobOpening  # noqa: E402

for w in WORLDS:
    for other in WORLDS:
        if other is w:
            continue
        foreign_job = other["rows"].get("job_opening")
        if foreign_job is None:
            continue
        try:
            sync_google_form_responses_for_job(w["organization"].pk, foreign_job.pk)
            refused, detail = False, "the task accepted another organization's job"
        except JobOpening.DoesNotExist:
            refused, detail = True, ""
        except Exception as exc:  # noqa: BLE001
            refused, detail = False, f"{type(exc).__name__}: {exc}"
        check(
            f"10. a task for {w['name']} refuses {other['name']}'s job opening",
            refused, detail,
        )


# ---------------------------------------------------------------------------
# 11. Dashboard aggregates are one organization's, stored and served
# ---------------------------------------------------------------------------
#
# The three organizations have DIFFERENT headcounts on purpose (20/15/10). A
# snapshot that summed two tenants and one that counted a single tenant would
# otherwise be told apart only by row ownership; a doubled number is the leak
# that matters, and it is visible in the value itself.

print()
print("=" * 72)
print("Dashboard aggregates")
print("=" * 72)

from apps.employees.models import Employee as _Emp  # noqa: E402
from apps.reporting.models import MetricSnapshot  # noqa: E402

TREND = "hr.headcount_trend"

for w in WORLDS:
    org = w["organization"]
    refresh_snapshots_for_organization(org.pk)

    with across_organizations():
        rows = list(MetricSnapshot.objects.all_orgs().filter(organization=org))
        own_headcount = (
            _Emp.objects.all_orgs().filter(organization=org, is_active=True).count()
        )
    latest = max(
        (r for r in rows if r.metric_key == TREND), key=lambda r: r.dimension["point"],
        default=None,
    )
    check(
        f"11. {w['name']}'s stored headcount is its own ({own_headcount})",
        latest is not None and int(latest.value) == own_headcount,
        f"stored {latest.value if latest else 'nothing'}, own headcount {own_headcount}",
    )
    check(
        f"11. every snapshot row written for {w['name']} belongs to it",
        bool(rows) and all(r.organization_id == org.pk for r in rows),
        len(rows),
    )

for w in WORLDS:
    client = CLIENTS[(w["slug"], "admin")]
    response = client.get(f"/api/v1/bi/{TREND}/")
    with across_organizations():
        own_headcount = (
            _Emp.objects.all_orgs()
            .filter(organization=w["organization"], is_active=True)
            .count()
        )
        others = [
            _Emp.objects.all_orgs()
            .filter(organization=o["organization"], is_active=True)
            .count()
            for o in WORLDS
            if o is not w
        ]
    served = []
    if response.status_code == 200:
        served = [p.get("value") for p in response.json().get("points", [])]
    check(
        f"11. {w['name']}'s dashboard reports its own headcount, not a sum",
        response.status_code == 200
        and served
        and served[-1] == own_headcount
        and all(served[-1] != own_headcount + other for other in others),
        f"{response.status_code} served {served[-3:]}, own {own_headcount}, others {others}",
    )


# ---------------------------------------------------------------------------
# 12. The cross-tenant defects found during the rollout, re-attempted
# ---------------------------------------------------------------------------
#
# Each of these was a real breach, found by this kind of probing and fixed.
# A fix without a standing attempt against it is a fix that can be undone
# silently, so every one is re-run here against the live system.

print()
print("=" * 72)
print("Defects found during the rollout")
print("=" * 72)

from django.core.management import call_command  # noqa: E402
from django.utils import timezone as _tz  # noqa: E402

from apps.accounts.models import Role as _Role  # noqa: E402
from apps.accounts.models import UserRole as _UserRole  # noqa: E402
from apps.audit.models import AuditAction as _AuditAction  # noqa: E402
from apps.audit.models import AuditLog as _AuditLog  # noqa: E402
from apps.payroll.models import PayrollRun as _PayrollRun  # noqa: E402
from apps.recruitment.models import Candidate as _Candidate  # noqa: E402
from apps.recruitment.models import LegalBasis as _LegalBasis  # noqa: E402
from core.access.context import resolve_context as _resolve_context  # noqa: E402

# 12a. A payroll run scoped to another organization's location. The view read
# `location` by hand, so relation scoping never saw it: Org A's run was created
# carrying Org B's location, and the response echoed B's location code. `None`
# means an organization-wide run, so the same lookup failing quietly would
# widen the run to every employee instead.
for w in WORLDS:
    client = CLIENTS[(w["slug"], "admin")]
    for other in WORLDS:
        if other is w:
            continue
        month = 7 + WORLDS.index(other)
        foreign = client.post(
            "/api/v1/payroll/runs/",
            {"period_year": 2025, "period_month": month,
             "location": str(other["rows"]["location"].pk)},
            format="json",
        )
        with across_organizations():
            made = _PayrollRun.objects.all_orgs().filter(
                organization=w["organization"], period_year=2025, period_month=month
            ).exists()
        control = client.post(
            "/api/v1/payroll/runs/",
            {"period_year": 2025, "period_month": month,
             "location": str(w["rows"]["location"].pk)},
            format="json",
        )
        check(
            f"12a. {w['name']} cannot scope a payroll run to {other['name']}'s location",
            foreign.status_code == 400
            and "location" in foreign.content.decode(errors="replace").lower()
            and not made,
            f"{foreign.status_code} {foreign.content[:140]}",
            inconclusive=control.status_code != 201,
        )

# 12b. `purge_candidates --organization <slug> --apply` anonymised every
# organization's overdue candidates, not just the named one's. Destructive, and
# run here for real against candidates this script created.
OVERDUE = {}
for w in WORLDS:
    with acting_as(None, organization=w["organization"]):
        overdue = _Candidate.objects.create(
            first_name="Overdue", last_name="Applicant",
            email=f"overdue@{w['domain']}", source="workindia",
            consent_given=False, legal_basis=_LegalBasis.VOLUNTARILY_PROVIDED,
            notice_due_at=_tz.now(),
        )
        # Aged INSIDE the binding: an unbound update matches no rows, so the
        # candidate would never become overdue and the purge below would have
        # nothing to do -- passing for the wrong reason, or failing for one.
        _Candidate.objects.all_orgs().filter(pk=overdue.pk).update(
            created_at=_tz.now() - dt.timedelta(days=400)
        )
    OVERDUE[w["slug"]] = overdue.pk

purged_for = WORLDS[0]
call_command("purge_candidates", organization=purged_for["slug"], apply=True)
with across_organizations():
    names = dict(
        _Candidate.objects.all_orgs()
        .filter(pk__in=OVERDUE.values())
        .values_list("pk", "first_name")
    )
check(
    f"12b. purging {purged_for['name']} anonymised its own overdue candidate",
    names.get(OVERDUE[purged_for["slug"]]) == "Redacted",
    names.get(OVERDUE[purged_for["slug"]]),
)
for w in WORLDS[1:]:
    check(
        f"12b. purging {purged_for['name']} left {w['name']}'s candidate intact",
        names.get(OVERDUE[w["slug"]]) == "Overdue",
        names.get(OVERDUE[w["slug"]]),
    )

# 12c. Authority was resolved from a user's role grants in EVERY organization,
# so one Admin grant row sitting in another organization made an ordinary
# employee an Admin in their own. The row is planted, asserted against, and
# hard-deleted.
for w in WORLDS:
    other = next(o for o in WORLDS if o is not w)
    with across_organizations():
        foreign_admin_role = _Role.objects.all_orgs().get(
            organization=other["organization"], code="admin"
        )
    planted = _UserRole(user=w["worker"], role=foreign_admin_role)
    with acting_as(None, organization=other["organization"]):
        _UserRole.objects.bulk_create([planted])
    try:
        ctx = _resolve_context(w["worker"])
        check(
            f"12c. a grant row in {other['name']} makes {w['name']}'s employee no Admin",
            "admin" not in ctx.role_codes
            and ctx.organization_id == w["organization"].pk,
            sorted(ctx.role_codes),
        )
    finally:
        with across_organizations():
            _UserRole.objects.all_orgs().filter(pk=planted.pk).hard_delete()

# 12d. The audit trail re-read a row through the tenant manager before an
# update. With nothing bound that raised, failing a save that carries its own
# organization; with another organization bound it found nothing and the update
# went UNAUDITED.
for w in WORLDS:
    subject = w["rows"]["employee"]
    # RELEASE 2: bound to the row's OWN organization rather than to nothing.
    # An unbound update now matches no rows at all -- the database's
    # fail-closed answer, and a stricter one than the manager gave. What this
    # case is about is unchanged: the audit re-read must not impose a tenant
    # question of its own on a row that already carries its organization.
    with acting_as(None, organization=w["organization"]):
        subject.phone = f"98{secrets.randbelow(10**8):08d}"
        try:
            subject.save(update_fields=["phone", "updated_at"])
            saved, why = True, ""
        except Exception as exc:  # noqa: BLE001
            saved, why = False, f"{type(exc).__name__}: {exc}"
        audited = _AuditLog.objects.filter(
            entity_type="employees.Employee",
            entity_id=str(subject.pk),
            action=_AuditAction.UPDATE,
        ).exists()
    check(
        f"12d. an update to {w['name']}'s employee is saved and audited "
        f"without the re-read imposing a tenant question",
        saved and audited,
        why or "no audit row was written",
    )


# ---------------------------------------------------------------------------
# 13. The report
# ---------------------------------------------------------------------------

# Guards the guard. A run that performs no attempts reports no failures, and
# "0 failures" is exactly what a passing run looks like at a glance -- so a
# script that quietly did nothing would be indistinguishable from proof. This
# is not hypothetical: piping this file into `manage.py shell` does precisely
# that, because IPython treats a blank line inside a block as the end of it.
#
# The floor rises with the script. It was 50 when sections 1-8 were all there
# was; sections 9-12 alone contribute one check per organization-owned model
# and one per shipped subtask, so a run that produced 50 now is a run that
# stopped somewhere in the middle.
if len(RESULTS) < 250 or not WALK or len(ORG_OWNED) < 90:
    raise SystemExit(
        f"verify_tenant_isolation: ONLY {len(RESULTS)} CHECKS RAN, "
        f"{len(WALK)} walks completed and {len(ORG_OWNED)} organization-owned "
        f"models were found. The script did not execute properly -- no report "
        f"has been written. Invoke it with "
        f"`manage.py shell -c \"exec(open(...).read())\"`, not with `shell < file`."
    )

passed = [r for r in RESULTS if r[1] == "PASS"]
failed = [r for r in RESULTS if r[1] == "FAIL"]
skipped = [r for r in RESULTS if r[1] == "SKIP"]

total_served = sum(row[2] for row in WALK)
total_refused = sum(row[3] for row in WALK)
total_leaked = sum(len(row[4]) for row in WALK)

lines = []
w_ = lines.append

w_("# Tenant Isolation Test Report")
w_("")
w_(f"Generated {timezone.now():%Y-%m-%d %H:%M %Z} by "
   "`scripts/verify_tenant_isolation.py`.")
w_("")
w_("This file is written by the script that performs the attempts. It is not a "
   "description of a test run; it is the output of one. Re-running the script "
   "overwrites it.")
w_("")
w_("## Verdict")
w_("")
if failed:
    w_(f"**FAILED.** {len(failed)} of {len(RESULTS)} checks did not pass.")
else:
    w_(f"**PASSED.** {len(passed)} of {len(RESULTS)} checks passed"
       + (f", {len(skipped)} inconclusive." if skipped else ", none inconclusive."))
w_("")
w_("| | |")
w_("|---|---|")
w_(f"| Checks passed | {len(passed)} |")
w_(f"| Checks failed | {len(failed)} |")
w_(f"| Inconclusive (positive control did not succeed) | {len(skipped)} |")
w_(f"| Detail routes walked across organizations | {total_served} |")
w_(f"| Refused | {total_refused} |")
w_(f"| Served another organization's row | {total_leaked} |")
w_(f"| Raised instead of answering | {len(set(ERRORED))} |")
w_(f"| Detail routes exposed by the URL resolver, in total | {ROUTES_TOTAL} |")
w_(f"| ...of which answered for the caller's own row, and were therefore "
   f"asked about | {WALK[0][2] if WALK else 0} |")
w_("")

w_("## The organizations")
w_("")
w_("Fictional, generated per run. Every domain is `.example` (RFC 2606, "
   "unroutable). Passwords are generated in memory and are not written to this "
   "file, to any file, or to the source.")
w_("")
w_("| Organization | Slug | Employees | Departments | Locations |")
w_("|---|---|---|---|---|")
for w2 in WORLDS:
    w_(f"| {w2['name']} | `{w2['slug']}` | {len(w2['employees'])} | "
       f"{len(w2['departments'])} | {len(w2['locations'])} |")
w_("")

w_("## What was attempted")
w_("")
w_("Each organization's **Admin** made every attempt. Admin deliberately: they "
   "hold `Scope.ALL` on almost every resource, which is precisely the authority "
   "the organization predicate has to override. A principal with less authority "
   "proves less.")
w_("")
w_("Every cross-organization attempt is paired with the same request against the "
   "caller's **own** equivalent row. An attempt whose control did not return 200 "
   "is reported as inconclusive, never as a pass -- a route that refuses "
   "everybody would otherwise read as perfect isolation.")
w_("")
w_("| Attempt | Refusal required |")
w_("|---|---|")
w_("| List employees, departments, locations, leave, attendance, payroll runs, "
   "candidates, documents, audit logs | no other organization's row present |")
w_("| Read a named employee, department, location, leave request, attendance "
   "record, payroll run, candidate, document, leave type | 404 |")
w_("| Edit another organization's employee | 404 |")
w_("| Create an employee in another organization's department, with a payload "
   "valid in every other field | 400, naming the department |")
w_("| Open an exit, or file a resignation, for another organization's employee "
   "(a relation id in the body of a custom endpoint) | 400 or 404, and the "
   "employee unchanged |")
w_("| Every detail route the URL resolver exposes | 403, 404 or 405 |")
w_("| The same read as HR Head and as a plain employee | 403 or 404 |")
w_("| Scope a payroll run to another organization's location | 400, naming the "
   "location, and no run created |")
w_("| Run each scheduled subtask for one organization | no other "
   "organization's rows changed |")
w_("| Hand a subtask another organization's job opening | raises, rather than "
   "quietly finding nothing |")
w_("| Purge one organization's overdue candidates | the others' left intact |")
w_("| Plant an Admin grant for one organization's employee in another | no "
   "Admin authority anywhere |")
w_("")

w_("### Why 404 and not 403")
w_("")
w_("A 403 answers \"that record exists and you may not see it\", which tells one "
   "customer that a record of another customer's exists. The requirement is that "
   "another organization's row is indistinguishable from a row that was never "
   "there. Detail reads that answered 403 are listed below separately rather "
   "than counted as passes.")
w_("")
if DISCLOSED_BY_403:
    w_("**Answered 403 where 404 is required:**")
    w_("")
    for caller, victim, key in DISCLOSED_BY_403:
        w_(f"- {caller} -> {victim} / {key}")
else:
    w_("No detail read answered 403. Every refusal was a 404.")
w_("")

w_("## The full route walk")
w_("")
w_("The nine resources above are a list somebody chose. This walk is derived "
   "from the URL resolver instead, so a route added next year is covered the day "
   "it is added. Each route is filled with a **real id of the right model** "
   "belonging to another organization -- a random UUID would 404 for absence and "
   "prove nothing.")
w_("")
w_("| Caller | Target | Routes that answered for the caller's own row | Refused | Served |")
w_("|---|---|---|---|---|")
for caller, victim, served, refused, leaked in WALK:
    w_(f"| {caller} | {victim} | {served} | {refused} | {len(leaked)} |")
w_("")
if total_leaked:
    w_("**Routes that served another organization's row:**")
    w_("")
    for caller, victim, _s, _r, leaked in WALK:
        for entry in leaked:
            w_(f"- {caller} -> {victim}: `{entry}`")
    w_("")

w_("## Routes that raised instead of answering")
w_("")
w_("An exception is not a refusal. Nothing was served, so no data crossed a "
   "boundary, but a view that cannot render a row is a bug and is recorded "
   "here rather than folded into the refused column.")
w_("")
if ERRORED:
    for entry in sorted(set(ERRORED)):
        w_(f"- `{entry}`")
else:
    w_("None. Every route answered with a status code.")
w_("")

w_("## Underneath the HTTP surface: the manager")
w_("")
w_("Sections 1-8 above are the request surface. This is the layer beneath it, "
   "and the one that covers what a view mixin cannot: two thirds of this "
   "codebase's queryset call sites are in services, reached from management "
   "commands and Celery as well as from requests, and DRF builds an unfiltered "
   "queryset behind every writable relational serializer field. Those never "
   "pass through a view. They do pass through the manager.")
w_("")
w_("Asked per model rather than once. \"The mechanism exists\" and \"the "
   "mechanism is attached to this table\" are different claims, and the first "
   "was true for a whole stage while the second was false of every table in "
   "the product.")
w_("")
w_("| | |")
w_("|---|---|")
w_(f"| Organization-owned models found in the app registry | {len(ORG_OWNED)} |")
w_(f"| Apps owning them | {len(MANAGER_APPS)} |")
w_(f"| Whose managers filter, refuse an unbound read, and keep `all_orgs()` | "
   f"{len([r for r in RESULTS if r[0].startswith('9. ') and r[1] == 'PASS']) - 1} |")
w_(f"| Apps | {', '.join(MANAGER_APPS)} |")
w_("")
w_("Refusing is the requirement, not returning nothing: an empty queryset "
   "inside a Celery task is indistinguishable from \"no work to do\", so the "
   "manager raises. `all_orgs()` is the deliberate, greppable escape for "
   "platform-wide work, and it must keep working or platform code has no way "
   "out.")
w_("")

w_("## Scheduled work")
w_("")
w_("Every per-organization subtask the product ships, run for one organization "
   "while the other two are watched for changes. The dispatchers themselves are "
   "not invoked here: they queue for every running organization on the "
   "deployment, which on a development database means somebody else's demo "
   "data. The subtask is where the tenancy lives.")
w_("")
w_("The case that matters is the last one. A task bound to one tenant and "
   "handed another's object id must RAISE. Silently finding nothing is "
   "indistinguishable from having no work to do, which is how a customer stops "
   "being processed for a month with nothing in any log -- and it is why the "
   "manager raises rather than returning an empty queryset.")
w_("")
for name, _task, _kw in SUBTASKS:
    passes = len([r for r in RESULTS if r[0].startswith(f"10. {name}") and r[1] == "PASS"])
    total = len([r for r in RESULTS if r[0].startswith(f"10. {name}")])
    w_(f"- `{name}` — {passes}/{total} checks passed")
w_("")

w_("## Dashboard aggregates")
w_("")
w_("A metric snapshot is an organisation-wide total, materialised nightly. The "
   "three organizations are deliberately different sizes, so a snapshot that "
   "summed two tenants is visible as a WRONG NUMBER rather than only as row "
   "ownership.")
w_("")
w_("| Organization | Active employees | Headcount stored | Headcount served |")
w_("|---|---|---|---|")
for w2 in WORLDS:
    org = w2["organization"]
    with across_organizations():
        own = _Emp.objects.all_orgs().filter(organization=org, is_active=True).count()
        stored = [
            r for r in MetricSnapshot.objects.all_orgs().filter(
                organization=org, metric_key=TREND
            )
        ]
    latest = max(stored, key=lambda r: r.dimension["point"], default=None)
    response = CLIENTS[(w2["slug"], "admin")].get(f"/api/v1/bi/{TREND}/")
    served = (
        response.json()["points"][-1]["value"]
        if response.status_code == 200 and response.json().get("points")
        else "—"
    )
    w_(f"| {w2['name']} | {own} | {int(latest.value) if latest else '—'} | {served} |")
w_("")

w_("## The defects this exercise found, re-attempted")
w_("")
w_("Each of these was a real cross-tenant breach, found by probing of this kind "
   "during the manager rollout and fixed. A fix with no standing attempt "
   "against it is a fix that can be undone silently, so each is re-run here "
   "against the live system rather than described.")
w_("")
w_("| Defect | What it did before | Re-attempted here |")
w_("|---|---|---|")
w_("| Payroll run location | `POST /payroll/runs/` read `location` by hand, so "
   "relation scoping never saw it: one organization's run was created carrying "
   "another's location, and the response echoed its code. An id that fails to "
   "resolve means \"organization-wide\", so a quiet miss would widen the run to "
   "every employee | 12a |")
w_("| Candidate retention purge | `purge_candidates --organization <slug> "
   "--apply` anonymised every organization's overdue candidates | 12b |")
w_("| Authority from anywhere | permissions were built from a user's role "
   "grants in EVERY organization, so one Admin grant row planted elsewhere made "
   "an ordinary employee an Admin at home, and the admin sign-in door let them "
   "in | 12c |")
w_("| Unaudited updates | the audit trail re-read a row through the tenant "
   "manager before an update: with nothing bound it raised, and with another "
   "organization bound it found nothing and wrote no audit record | 12d |")
w_("")

w_("## Every check")
w_("")
w_("| Result | Check | Detail |")
w_("|---|---|---|")
for name, status, detail in RESULTS:
    safe = detail.replace("|", "\\|").replace("\n", " ")[:160]
    w_(f"| {status} | {name} | {safe} |")
w_("")

w_("## What this does not prove")
w_("")
w_("Stated because a report that only lists what passed is not evidence, it is "
   "advertising.")
w_("")
w_("- **The organizations are provisioned by the platform service, but their "
   "DATA is not created through the API.** `provision_organization` builds each "
   "one exactly as the console does for a real customer -- configuration seeds, "
   "first administrator, audit row, invitation -- and each goes live through "
   "`finish_setup`. The departments, people, payroll run and candidates the "
   "walk aims at are then written directly, because they are the targets of "
   "the proof rather than its subject; whether the application's own create "
   "endpoints keep a row in its organization is the write-injection matrix's "
   "job, not this report's.")
w_(f"- **The walk reached {WALK[0][2] if WALK else 0} of the {ROUTES_TOTAL} "
   f"routes the resolver exposes.** A route is only asserted against when it "
   f"serves the CALLER's own row, because one that answers 405 or 404 for "
   f"everybody refuses both organizations equally and counting it as a "
   f"refusal would score the test against itself. The rest are dropped for "
   f"lack of an answer, not judged and passed. Most of the gap is "
   f"POST/PUT-only actions, file downloads with nothing uploaded, and the "
   f"`.json` suffix duplicates of routes already walked.")
w_("- **The dispatchers are not run, only the subtasks they queue.** `fan_out` "
   "queues for every running organization on the deployment, which on a "
   "development database means data this script did not create. The pairing "
   "between a beat row and its subtask is asserted by the suite instead.")
w_("- **Per-organization email, files and configuration are not covered here.** "
   "They have their own tests: no message addressed outside the acting "
   "organization, every upload under its own organization's subtree, and every "
   "resolver taking an explicit organization.")
w_("- **The platform boundary is not covered here.** Whether a platform "
   "administrator is kept out of customer HR data is asserted by the platform "
   "layer's own tests: they hold no role grant in any organization, so every "
   "tenant queryset resolves to nothing and every tenant route refuses them.")
w_("- **A passing report is evidence about this build, not a proof of the "
   "design.** It re-runs on demand; it does not run on every commit. The gate "
   "that does is the suite.")
w_("")

report_path = Path(settings.BASE_DIR).parent.parent / "TENANT_ISOLATION_TEST_REPORT.md"
report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

print()
print("=" * 72)
print(f"{len(passed)}/{len(RESULTS)} checks passed"
      + (f", {len(failed)} FAILED" if failed else "")
      + (f", {len(skipped)} inconclusive" if skipped else ""))
print(f"Route walk: {total_refused}/{total_served} refused, {total_leaked} served")
print(f"Report written to {report_path}")
print("=" * 72)
if failed:
    for name, _s, detail in failed:
        print(f"  FAILED: {name}  :: {detail[:160]}")
