"""
Prove tenant isolation against a running system, and write down what happened.

    cd apps/api
    python manage.py shell -c "exec(open('../../scripts/verify_tenant_isolation.py').read())"

Not `shell < script`. With IPython installed, Django's shell reads a redirected
file as if somebody were typing it, and a blank line inside an indented block
ends the block -- so the loops below silently do not run and the script reports
zero checks and zero failures, which is the most dangerous output it could
possibly produce. `exec()` compiles the whole file at once.

Three organizations are provisioned, populated with fictional HR data, and then
every one of them is told to go and fetch the others' records -- as its own
Admin, who holds Scope.ALL almost everywhere and is therefore the principal
with the most reach to override. Every attempt must be refused.

The output is `TENANT_ISOLATION_TEST_REPORT.md` at the repository root, written
from the results rather than from a description of them. That is the whole
point of the script: the brief asks not to be told the system is multi-tenant
but to be shown, and a document generated by the attempts themselves cannot
claim an attempt that was never made.

WHAT COUNTS AS A REFUSAL
------------------------
404, not 403. A 403 says "this exists and you may not have it", which tells
one customer that a record of another exists -- so the requirement is that
another organization's row is indistinguishable from a row that was never
there. The script records the distinction and reports 403s separately rather
than counting them as passes.

WHY EACH REFUSAL IS PAIRED WITH A POSITIVE CONTROL
--------------------------------------------------
A route that refuses everybody proves nothing about tenancy. Every cross-org
attempt below is preceded by the same request against the caller's OWN
equivalent row, and an attempt whose control did not succeed is reported as
INCONCLUSIVE rather than as a pass. Without that, a typo in a URL reads as
perfect isolation.

NO REAL DATA
------------
Every name, address and email here is invented, every domain is `.example`
(reserved by RFC 2606 and unroutable), and passwords are generated per run and
never written down -- not to a file, not to this source, not to the report.
"""

import datetime as dt
import secrets
import sys
from collections import Counter
from decimal import Decimal
from pathlib import Path

from django.conf import settings
from django.utils import timezone
from rest_framework.test import APIClient

from core.access.routewalk import concretize, detail_routes, model_of, rows_for
from core.middleware import acting_as

sys.stdout.reconfigure(encoding="utf-8")

#: Unique per run, so the script is re-runnable against the same database
#: without colliding with the organizations it made last time.
NONCE = secrets.token_hex(3)

RESULTS = []


def check(name, ok, detail="", *, inconclusive=False):
    status = "SKIP" if inconclusive else ("PASS" if ok else "FAIL")
    RESULTS.append((name, status, str(detail)[:300]))
    line = f"{status} {name}"
    if status != "PASS" and detail:
        line += f"  :: {str(detail)[:200]}"
    print(line)
    return ok


# ---------------------------------------------------------------------------
# 1. Three organizations, sized as the brief asks
# ---------------------------------------------------------------------------

#: (slug, display name, employees, departments, locations). The sizes are the
#: brief's. The industries are the brief's too, and they matter beyond
#: flavour: three different shapes of company is what stops the proof being
#: "two copies of the same fixture agree with each other".
PROFILES = [
    ("healthcare", "Northwind Health", 20, 5, 3),
    ("technology", "Aperture Systems", 15, 4, 2),
    ("retail", "Fairhaven Retail", 10, 3, 2),
]

DEPARTMENT_NAMES = ["People", "Finance", "Operations", "Technology", "Support"]
CITIES = [("Pune", "MH"), ("Bengaluru", "KA"), ("Jaipur", "RJ")]
FIRST_NAMES = [
    "Aditi", "Bhavna", "Chetan", "Devika", "Esha", "Farhan", "Gaurav", "Hema",
    "Imran", "Jaya", "Kabir", "Leela", "Manav", "Nisha", "Omkar", "Preeti",
    "Rahul", "Sanya", "Tarun", "Uma",
]
LAST_NAMES = ["Rao", "Menon", "Iyer", "Bose", "Kulkarni", "Nair", "Verma", "Sen"]


def provision(slug_base, name, n_employees, n_departments, n_locations):
    """
    One complete organization with its own everything.

    THIS FUNCTION IS THE SEAM. When the platform provisioning service lands it
    replaces the body wholesale -- an organization is created by one atomic
    service call, not by a script reaching into the ORM. Until then this builds
    the same shape by hand so the isolation proof does not have to wait for the
    platform layer to exist.
    """
    from apps.accounts.models import Role, User, UserRole
    from apps.accounts.services.roles import seed_roles
    from apps.assets.models import Asset, AssetCategory
    from apps.attendance.models import AttendanceRecord
    from apps.employees.models import Employee
    from apps.leave.models import LeaveRequest, LeaveType
    from apps.organization.models import (
        Department,
        Designation,
        EmployeeLevel,
        Location,
        Organization,
        OrganizationMembership,
        OrgStatus,
    )
    from apps.payroll.models import PayrollRun
    from apps.recruitment.models import Candidate
    from core.access.catalog import DepartmentKind, Layer

    # Imported from the test tree ON PURPOSE, and it is worth saying why. Both
    # this script and `tests/tenancy/test_route_walker.py` need the same thing:
    # an organization populated broadly enough that the route walk can ask
    # about payroll, recruitment, offboarding and the rest rather than about
    # departments six times. Two definitions of that would drift, and the one
    # that drifted would be this one -- the proof, not the gate, because the
    # gate runs on every commit and this does not. Sharing one builder means
    # the report cannot quietly cover less than the suite does.
    from tests.tenancy._extra import build_extra_rows

    slug = f"{slug_base}-{NONCE}"
    domain = f"{slug}.example"
    org = Organization.objects.create(name=name, slug=slug, status=OrgStatus.ACTIVE)

    world = {"organization": org, "name": name, "slug": slug, "domain": domain,
             "passwords": {}, "rows": {}}

    with acting_as(None, organization=org):
        seed_roles(organization=org)
        roles = {r.code: r for r in Role.objects.filter(organization=org)}

        locations = [
            Location.objects.create(
                name=f"{name} {CITIES[i][0]}", code=f"L{i + 1}",
                city=CITIES[i][0], state=CITIES[i][1], is_head_office=(i == 0),
            )
            for i in range(n_locations)
        ]
        departments = [
            Department.objects.create(
                name=DEPARTMENT_NAMES[i], code=f"D{i + 1}",
                kind=DepartmentKind.HR if i == 0 else DepartmentKind.OPERATIONS,
            )
            for i in range(n_departments)
        ]
        level = EmployeeLevel.objects.create(name="Staff", code="L5", layer=Layer.STAFF)
        designation = Designation.objects.create(title="Officer", department=None)

        def make_user(role_code, local):
            password = secrets.token_urlsafe(18)
            user = User.objects.create_user(
                email=f"{local}@{domain}", password=password,
                first_name=role_code.replace("_", " ").title(), last_name=name.split()[0],
            )
            UserRole.objects.create(user=user, role=roles[role_code])
            OrganizationMembership.objects.create(organization=org, user=user)
            world["passwords"][user.email] = password
            return user

        admin = make_user("admin", "admin")
        hr = make_user("hr_head", "hr")
        worker = make_user("employee", "employee")

        employees = []
        for i in range(n_employees):
            linked = {0: hr, 1: worker}.get(i)
            employees.append(
                Employee.objects.create(
                    employee_code=f"EMP{i + 1:03d}",
                    user=linked,
                    first_name=FIRST_NAMES[i % len(FIRST_NAMES)],
                    last_name=LAST_NAMES[i % len(LAST_NAMES)],
                    department=departments[i % n_departments],
                    designation=designation,
                    location=locations[i % n_locations],
                    level=level,
                    date_of_joining=dt.date(2024, 1, 1),
                )
            )

        subject = employees[1]
        # No user and no role: the offboarding rows hang off this one, so the
        # employee the rest of the checks use is not simultaneously resigning.
        spare = Employee.objects.create(
            employee_code=f"EMP{n_employees + 1:03d}",
            first_name="Spare", last_name=name.split()[0],
            department=departments[0], designation=designation,
            location=locations[0], level=level,
            date_of_joining=dt.date(2024, 1, 1),
        )
        leave_type = LeaveType.objects.create(name="Casual Leave", code="CL")

        world["admin"], world["hr"], world["worker"] = admin, hr, worker
        world["employees"] = employees
        world["departments"] = departments
        world["locations"] = locations
        world["rows"] = {
            "employee": subject,
            "department": departments[0],
            "location": locations[0],
            "leave_type": leave_type,
            "leave_request": LeaveRequest.objects.create(
                employee=subject, leave_type=leave_type,
                start_date=dt.date(2025, 6, 2), end_date=dt.date(2025, 6, 2),
                days=Decimal("1.0"), reason="Isolation fixture",
            ),
            "attendance_record": AttendanceRecord.objects.create(
                employee=subject, date=dt.date(2025, 6, 3)
            ),
            "payroll_run": PayrollRun.objects.create(
                period_year=2025, period_month=6, run_by=hr
            ),
            "candidate": Candidate.objects.create(
                first_name="Ira", last_name="Dutta",
                email=f"applicant@{domain}", consent_given=True,
            ),
            # `employee_document` and `document_type` come from the shared
            # builder below, which already creates both -- creating them here
            # too collided on the per-organization uniqueness of the code.
            "asset": Asset.objects.create(
                asset_tag="AST-001",
                category=AssetCategory.objects.create(name="Laptops", code="LAPTOP"),
                name="ThinkPad",
            ),
        }

        # The rest of the product -- offboarding, onboarding, hiring workflows,
        # recruitment, payroll detail, devices, imports, audit. Without these
        # the walk below asks about nine kinds of object and stays silent about
        # everything else, which is not what this report should be claiming.
        world["rows"].update(
            build_extra_rows(
                organization=org,
                slug=slug,
                roles=roles,
                department=departments[0],
                location=locations[0],
                designation=designation,
                level=level,
                hr=hr,
                hr_employee=employees[0],
                worker_employee=subject,
                spare_employee=spare,
                leave_type=leave_type,
                asset=world["rows"]["asset"],
                candidate=world["rows"]["candidate"],
                payroll_run=world["rows"]["payroll_run"],
            )
        )
    return world


print("=" * 72)
print("Provisioning three organizations")
print("=" * 72)

WORLDS = [provision(*profile) for profile in PROFILES]

for w in WORLDS:
    check(
        f"1. {w['name']} provisioned ({len(w['employees'])} employees, "
        f"{len(w['departments'])} departments, {len(w['locations'])} locations)",
        len(w["employees"]) > 0 and len(w["rows"]) >= 9,
    )


#: Routes that raised instead of answering. An exception is not a refusal --
#: it is a bug -- so these are counted and reported separately rather than
#: quietly folded into either column.
ERRORED = []


def get(client, path):
    """
    A GET that returns a status instead of raising.

    The walk touches every detail route in the product. One view raising --
    a missing file on disk, a serializer that cannot render a half-built row --
    would otherwise abort the run and produce no report at all, which is the
    one outcome worse than a failing report.
    """
    try:
        return client.get(path).status_code
    except Exception as exc:  # noqa: BLE001 -- deliberately broad; see docstring
        ERRORED.append(f"{path} :: {type(exc).__name__}: {exc}")
        return None


def login(world, who):
    user = world[who]
    client = APIClient(HTTP_HOST="localhost")
    response = client.post(
        "/api/v1/auth/login/",
        {"email": user.email, "password": world["passwords"][user.email]},
        format="json",
    )
    if response.status_code != 200:
        return None
    client.credentials(HTTP_AUTHORIZATION="Bearer " + response.json()["access"])
    return client


CLIENTS = {}
for w in WORLDS:
    for who in ("admin", "hr", "worker"):
        client = login(w, who)
        CLIENTS[(w["slug"], who)] = client
        check(f"2. {w['name']} / {who} signs in", client is not None)


# ---------------------------------------------------------------------------
# 3. Each principal resolves to its OWN organization
# ---------------------------------------------------------------------------

for w in WORLDS:
    client = CLIENTS[(w["slug"], "admin")]
    if client is None:
        check(f"3. {w['name']} admin resolves to its own organization", False,
              "could not sign in")
        continue
    branding = client.get("/api/v1/org/branding/?org=" + w["slug"])
    check(
        f"3. {w['name']} admin's own organization answers",
        branding.status_code == 200 and branding.json().get("name") == w["name"],
        branding.content[:160],
    )


# ---------------------------------------------------------------------------
# 4. Lists contain the caller's rows and nobody else's
# ---------------------------------------------------------------------------

LIST_ROUTES = {
    "employees": "/api/v1/employees/",
    "departments": "/api/v1/departments/",
    "locations": "/api/v1/locations/",
    "leave requests": "/api/v1/leave-requests/",
    "attendance": "/api/v1/attendance-records/",
    "payroll runs": "/api/v1/payroll/runs/",
    "candidates": "/api/v1/candidates/",
    "documents": "/api/v1/employee-documents/",
    "audit logs": "/api/v1/audit/",
}


def ids_in(payload):
    rows = payload.get("data", payload) if isinstance(payload, dict) else payload
    if not isinstance(rows, list):
        return set()
    return {str(r.get("id")) for r in rows if isinstance(r, dict) and "id" in r}


print()
print("=" * 72)
print("Cross-organization list reads")
print("=" * 72)

LIST_FINDINGS = []
for w in WORLDS:
    client = CLIENTS[(w["slug"], "admin")]
    others = [o for o in WORLDS if o is not w]
    for label, path in LIST_ROUTES.items():
        response = client.get(path)
        if response.status_code != 200:
            check(f"4. {w['name']} lists {label}", False, response.status_code,
                  inconclusive=True)
            continue
        seen = ids_in(response.json())
        foreign = set()
        for other in others:
            for row in other["rows"].values():
                if str(row.pk) in seen:
                    foreign.add(f"{other['name']}:{row.pk}")
            for employee in other["employees"]:
                if str(employee.pk) in seen:
                    foreign.add(f"{other['name']}:{employee.pk}")
        if foreign:
            LIST_FINDINGS.append((w["name"], label, sorted(foreign)))
        check(f"4. {w['name']}'s {label} list contains no other organization's rows",
              not foreign, sorted(foreign))


# ---------------------------------------------------------------------------
# 5. Detail reads of a named row belonging to somebody else
# ---------------------------------------------------------------------------

DETAIL_ROUTES = {
    "employee": "/api/v1/employees/{}/",
    "department": "/api/v1/departments/{}/",
    "location": "/api/v1/locations/{}/",
    "leave_request": "/api/v1/leave-requests/{}/",
    "attendance_record": "/api/v1/attendance-records/{}/",
    "payroll_run": "/api/v1/payroll/runs/{}/",
    "candidate": "/api/v1/candidates/{}/",
    "employee_document": "/api/v1/employee-documents/{}/",
    "leave_type": "/api/v1/leave-types/{}/",
}

print()
print("=" * 72)
print("Cross-organization detail reads")
print("=" * 72)

STATUS_TALLY = Counter()
LEAKS = []
DISCLOSED_BY_403 = []

for w in WORLDS:
    client = CLIENTS[(w["slug"], "admin")]
    for other in WORLDS:
        if other is w:
            continue
        for key, template in DETAIL_ROUTES.items():
            # The positive control, first and every time: the SAME route
            # against this caller's own row. A refusal below means nothing
            # unless this succeeded.
            control = get(client, template.format(w["rows"][key].pk))
            attempt = get(client, template.format(other["rows"][key].pk))
            STATUS_TALLY[attempt] += 1
            name = (f"5. {w['name']} reading {other['name']}'s {key}")
            if control != 200:
                check(name, False, f"control returned {control}", inconclusive=True)
                continue
            if attempt == 200:
                LEAKS.append((w["name"], other["name"], key, attempt))
                check(name, False, "SERVED IT (200)")
            elif attempt == 403:
                DISCLOSED_BY_403.append((w["name"], other["name"], key))
                check(name, False, "403 confirms the row exists; 404 required")
            else:
                check(name, attempt == 404, attempt)


# ---------------------------------------------------------------------------
# 6. Writes: neither editing another organization's row nor borrowing its ids
# ---------------------------------------------------------------------------

print()
print("=" * 72)
print("Cross-organization writes")
print("=" * 72)

for w in WORLDS:
    client = CLIENTS[(w["slug"], "admin")]
    for other in WORLDS:
        if other is w:
            continue

        patch = client.patch(
            f"/api/v1/employees/{other['rows']['employee'].pk}/",
            {"phone": "9000000000"}, format="json",
        )
        check(
            f"6. {w['name']} cannot edit {other['name']}'s employee",
            patch.status_code == 404, patch.status_code,
        )

        # The injection vector: a well-formed create naming ANOTHER
        # organization's department. Refusing this is what stops a valid
        # request from quietly stitching two tenants together.
        #
        # The payload must be valid in EVERY other respect. An earlier version
        # of this check sent `department` instead of `department_id` and left
        # out `email` and `role_code`, so every run was refused for the missing
        # fields and reported PASS without the department ever being looked at.
        # Refused-for-the-right-reason is asserted below, and a positive control
        # with the caller's own department makes an incomplete payload show up
        # as INCONCLUSIVE instead of as isolation.
        def _employee_payload(world, department_pk, tag):
            token = secrets.token_hex(3)
            return {
                "first_name": "Injected", "last_name": f"Row{tag}",
                "email": f"injected-{tag}-{token}@{world['domain']}",
                "personal_email": f"injected-{tag}-{token}.personal@{world['domain']}",
                "role_code": "employee",
                "department_id": str(department_pk),
                "designation_id": str(world["rows"]["employee"].designation_id),
                "location_id": str(world["rows"]["location"].pk),
                "level_id": str(world["rows"]["employee"].level_id),
                "reporting_manager_id": str(world["rows"]["employee"].pk),
                "date_of_joining": "2025-01-01",
            }

        control = client.post(
            "/api/v1/employees/",
            _employee_payload(w, w["rows"]["department"].pk, "own"),
            format="json",
        )
        created = client.post(
            "/api/v1/employees/",
            _employee_payload(w, other["rows"]["department"].pk, "foreign"),
            format="json",
        )
        body = created.content.decode(errors="replace").lower()
        check(
            f"6b. {w['name']} cannot create an employee in {other['name']}'s department",
            created.status_code == 400 and "department" in body,
            f"{created.status_code} {created.content[:140]}",
            inconclusive=control.status_code != 201,
        )

        # Relation ids in the body of a CUSTOM endpoint. This is the vector the
        # checks above never tried, and it was open: a declared
        # `PrimaryKeyRelatedField` on a plain Serializer resolved any
        # organization's employee, and `POST /exits/` then offboarded them --
        # status set to resigned, login and mailbox flagged, a settlement
        # created. The victim's state is re-read from the database, because a
        # 400 that still changed the row would not be a refusal.
        import datetime as _dt

        from apps.employees.models import Employee as _Employee
        from apps.offboarding.models import ExitWorkflow as _ExitWorkflow

        victim = other["rows"]["employee"]
        # A different employee of the caller's for each other organization. The
        # control files a real resignation, and a second one for the same person
        # is refused as already awaiting review -- which read as INCONCLUSIVE on
        # every second pass through this loop.
        other_index = next(i for i, candidate in enumerate(WORLDS) if candidate is other)
        own_subject = w["employees"][-1 - other_index]
        in_thirty_days = str(_dt.date.today() + _dt.timedelta(days=30))
        exit_type = _ExitWorkflow._meta.get_field("exit_type").choices[0][0]

        def _victim_state(victim_pk):
            row = _Employee.objects.all_orgs().get(pk=victim_pk)
            return (row.status, row.is_active)

        before = _victim_state(victim.pk)
        foreign_exit = client.post(
            "/api/v1/exits/",
            {"employee": str(victim.pk), "exit_type": exit_type,
             "last_working_date": in_thirty_days},
            format="json",
        )
        check(
            f"6c. {w['name']} cannot offboard {other['name']}'s employee",
            foreign_exit.status_code in (400, 404)
            and "employee" in foreign_exit.content.decode(errors="replace").lower()
            and _victim_state(victim.pk) == before,
            f"{foreign_exit.status_code} {foreign_exit.content[:140]}",
        )

        foreign_resignation = client.post(
            "/api/v1/resignations/",
            {"employee": str(victim.pk),
             "requested_last_working_date": in_thirty_days, "reason": "probe"},
            format="json",
        )
        own_resignation = client.post(
            "/api/v1/resignations/",
            {"employee": str(own_subject.pk),
             "requested_last_working_date": in_thirty_days, "reason": "control"},
            format="json",
        )
        check(
            f"6d. {w['name']} cannot file a resignation for {other['name']}'s employee",
            foreign_resignation.status_code in (400, 404)
            and "employee" in foreign_resignation.content.decode(errors="replace").lower()
            and _victim_state(victim.pk) == before,
            f"{foreign_resignation.status_code} {foreign_resignation.content[:140]}",
            inconclusive=own_resignation.status_code != 201,
        )


# ---------------------------------------------------------------------------
# 7. The whole detail surface, not the nine routes chosen above
# ---------------------------------------------------------------------------

print()
print("=" * 72)
print("Full route walk")
print("=" * 72)

EXCLUDED = ("/api/v1/auth/", "/api/v1/bootstrap/")

ROUTES_TOTAL = len(detail_routes())


def walk(caller, victim):
    """Every detail route the caller can answer, asked for the victim's row."""
    client = CLIENTS[(caller["slug"], "admin")]
    served, refused, leaked = 0, 0, []
    for template, view in detail_routes():
        if "pk" not in template:
            continue
        model = model_of(view)
        if model is None or not hasattr(model, "organization_id"):
            continue
        mine = rows_for(model, caller["organization"].pk).first()
        theirs = rows_for(model, victim["organization"].pk).first()
        if mine is None or theirs is None:
            continue
        my_path = concretize(template, mine.pk)
        their_path = concretize(template, theirs.pk)
        if not my_path or not their_path or my_path.startswith(EXCLUDED):
            continue
        # Only routes that answer for the caller's OWN row can distinguish a
        # tenancy refusal from a route that refuses everyone.
        if get(client, my_path) != 200:
            continue
        served += 1
        status = get(client, their_path)
        if status in (403, 404, 405):
            refused += 1
        elif status is None:
            pass  # raised rather than answered; counted in ERRORED, not here
        else:
            leaked.append(f"{status} {their_path} ({view.__name__} -> {model._meta.label})")
    return served, refused, leaked


WALK = []
for w in WORLDS:
    for other in WORLDS:
        if other is w:
            continue
        served, refused, leaked = walk(w, other)
        WALK.append((w["name"], other["name"], served, refused, leaked))
        check(
            f"7. {w['name']} -> {other['name']}: {refused}/{served} detail routes refused",
            not leaked and served > 0,
            leaked or "no route served the caller's own row",
        )


# ---------------------------------------------------------------------------
# 8. A non-admin has no wider reach than the admin who was already refused
# ---------------------------------------------------------------------------

print()
print("=" * 72)
print("Lesser principals")
print("=" * 72)

for w in WORLDS:
    for who in ("hr", "worker"):
        client = CLIENTS[(w["slug"], who)]
        for other in WORLDS:
            if other is w:
                continue
            status = get(client, f"/api/v1/employees/{other['rows']['employee'].pk}/")
            check(
                f"8. {w['name']} / {who} cannot read {other['name']}'s employee",
                status in (403, 404), status,
            )


# ---------------------------------------------------------------------------
# 9. The report
# ---------------------------------------------------------------------------

# Guards the guard. A run that performs no attempts reports no failures, and
# "0 failures" is exactly what a passing run looks like at a glance -- so a
# script that quietly did nothing would be indistinguishable from proof. This
# is not hypothetical: piping this file into `manage.py shell` does precisely
# that, because IPython treats a blank line inside a block as the end of it.
if len(RESULTS) < 50 or not WALK:
    raise SystemExit(
        f"verify_tenant_isolation: ONLY {len(RESULTS)} CHECKS RAN and "
        f"{len(WALK)} walks completed. The script did not execute properly -- "
        f"no report has been written. Invoke it with "
        f"`manage.py shell -c \"exec(open(...).read())\"`, not with `shell < file`."
    )

passed = [r for r in RESULTS if r[1] == "PASS"]
failed = [r for r in RESULTS if r[1] == "FAIL"]
skipped = [r for r in RESULTS if r[1] == "SKIP"]

total_served = sum(row[2] for row in WALK)
total_refused = sum(row[3] for row in WALK)
total_leaked = sum(len(row[4]) for row in WALK)

lines = []
w_ = lines.append

w_("# Tenant Isolation Test Report")
w_("")
w_(f"Generated {timezone.now():%Y-%m-%d %H:%M %Z} by "
   "`scripts/verify_tenant_isolation.py`.")
w_("")
w_("This file is written by the script that performs the attempts. It is not a "
   "description of a test run; it is the output of one. Re-running the script "
   "overwrites it.")
w_("")
w_("## Verdict")
w_("")
if failed:
    w_(f"**FAILED.** {len(failed)} of {len(RESULTS)} checks did not pass.")
else:
    w_(f"**PASSED.** {len(passed)} of {len(RESULTS)} checks passed"
       + (f", {len(skipped)} inconclusive." if skipped else ", none inconclusive."))
w_("")
w_("| | |")
w_("|---|---|")
w_(f"| Checks passed | {len(passed)} |")
w_(f"| Checks failed | {len(failed)} |")
w_(f"| Inconclusive (positive control did not succeed) | {len(skipped)} |")
w_(f"| Detail routes walked across organizations | {total_served} |")
w_(f"| Refused | {total_refused} |")
w_(f"| Served another organization's row | {total_leaked} |")
w_(f"| Raised instead of answering | {len(set(ERRORED))} |")
w_(f"| Detail routes exposed by the URL resolver, in total | {ROUTES_TOTAL} |")
w_(f"| ...of which answered for the caller's own row, and were therefore "
   f"asked about | {WALK[0][2] if WALK else 0} |")
w_("")

w_("## The organizations")
w_("")
w_("Fictional, generated per run. Every domain is `.example` (RFC 2606, "
   "unroutable). Passwords are generated in memory and are not written to this "
   "file, to any file, or to the source.")
w_("")
w_("| Organization | Slug | Employees | Departments | Locations |")
w_("|---|---|---|---|---|")
for w2 in WORLDS:
    w_(f"| {w2['name']} | `{w2['slug']}` | {len(w2['employees'])} | "
       f"{len(w2['departments'])} | {len(w2['locations'])} |")
w_("")

w_("## What was attempted")
w_("")
w_("Each organization's **Admin** made every attempt. Admin deliberately: they "
   "hold `Scope.ALL` on almost every resource, which is precisely the authority "
   "the organization predicate has to override. A principal with less authority "
   "proves less.")
w_("")
w_("Every cross-organization attempt is paired with the same request against the "
   "caller's **own** equivalent row. An attempt whose control did not return 200 "
   "is reported as inconclusive, never as a pass -- a route that refuses "
   "everybody would otherwise read as perfect isolation.")
w_("")
w_("| Attempt | Refusal required |")
w_("|---|---|")
w_("| List employees, departments, locations, leave, attendance, payroll runs, "
   "candidates, documents, audit logs | no other organization's row present |")
w_("| Read a named employee, department, location, leave request, attendance "
   "record, payroll run, candidate, document, leave type | 404 |")
w_("| Edit another organization's employee | 404 |")
w_("| Create an employee in another organization's department, with a payload "
   "valid in every other field | 400, naming the department |")
w_("| Open an exit, or file a resignation, for another organization's employee "
   "(a relation id in the body of a custom endpoint) | 400 or 404, and the "
   "employee unchanged |")
w_("| Every detail route the URL resolver exposes | 403, 404 or 405 |")
w_("| The same read as HR Head and as a plain employee | 403 or 404 |")
w_("")

w_("### Why 404 and not 403")
w_("")
w_("A 403 answers \"that record exists and you may not see it\", which tells one "
   "customer that a record of another customer's exists. The requirement is that "
   "another organization's row is indistinguishable from a row that was never "
   "there. Detail reads that answered 403 are listed below separately rather "
   "than counted as passes.")
w_("")
if DISCLOSED_BY_403:
    w_("**Answered 403 where 404 is required:**")
    w_("")
    for caller, victim, key in DISCLOSED_BY_403:
        w_(f"- {caller} -> {victim} / {key}")
else:
    w_("No detail read answered 403. Every refusal was a 404.")
w_("")

w_("## The full route walk")
w_("")
w_("The nine resources above are a list somebody chose. This walk is derived "
   "from the URL resolver instead, so a route added next year is covered the day "
   "it is added. Each route is filled with a **real id of the right model** "
   "belonging to another organization -- a random UUID would 404 for absence and "
   "prove nothing.")
w_("")
w_("| Caller | Target | Routes that answered for the caller's own row | Refused | Served |")
w_("|---|---|---|---|---|")
for caller, victim, served, refused, leaked in WALK:
    w_(f"| {caller} | {victim} | {served} | {refused} | {len(leaked)} |")
w_("")
if total_leaked:
    w_("**Routes that served another organization's row:**")
    w_("")
    for caller, victim, _s, _r, leaked in WALK:
        for entry in leaked:
            w_(f"- {caller} -> {victim}: `{entry}`")
    w_("")

w_("## Routes that raised instead of answering")
w_("")
w_("An exception is not a refusal. Nothing was served, so no data crossed a "
   "boundary, but a view that cannot render a row is a bug and is recorded "
   "here rather than folded into the refused column.")
w_("")
if ERRORED:
    for entry in sorted(set(ERRORED)):
        w_(f"- `{entry}`")
else:
    w_("None. Every route answered with a status code.")
w_("")

w_("## Every check")
w_("")
w_("| Result | Check | Detail |")
w_("|---|---|---|")
for name, status, detail in RESULTS:
    safe = detail.replace("|", "\\|").replace("\n", " ")[:160]
    w_(f"| {status} | {name} | {safe} |")
w_("")

w_("## What this does not prove")
w_("")
w_("Stated because a report that only lists what passed is not evidence, it is "
   "advertising.")
w_("")
w_("- **The organizations are built by this script, not by the platform "
   "provisioning service**, which does not exist yet. `provision()` is the seam: "
   "when that service lands, it replaces the body of that function and this "
   "report starts proving the real creation path too.")
w_(f"- **The walk reached {WALK[0][2] if WALK else 0} of the {ROUTES_TOTAL} "
   f"routes the resolver exposes.** A route is only asserted against when it "
   f"serves the CALLER's own row, because one that answers 405 or 404 for "
   f"everybody refuses both organizations equally and counting it as a "
   f"refusal would score the test against itself. The rest are dropped for "
   f"lack of an answer, not judged and passed. Most of the gap is "
   f"POST/PUT-only actions, file downloads with nothing uploaded, and the "
   f"`.json` suffix duplicates of routes already walked.")
w_("- **Celery tasks are not exercised here.** A task's isolation is a separate "
   "question with its own per-task tests, including the negative case where a "
   "task given another organization's object id must fail rather than silently "
   "do nothing.")
w_("- **Per-organization email, files and configuration are not covered.** Those "
   "arrive with the per-organization configuration work and get their own "
   "checks.")
w_("- **The platform layer is not covered**, because it does not exist yet. "
   "Whether a platform administrator is kept out of customer HR data is a "
   "question this report cannot yet answer.")
w_("")

report_path = Path(settings.BASE_DIR).parent.parent / "TENANT_ISOLATION_TEST_REPORT.md"
report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

print()
print("=" * 72)
print(f"{len(passed)}/{len(RESULTS)} checks passed"
      + (f", {len(failed)} FAILED" if failed else "")
      + (f", {len(skipped)} inconclusive" if skipped else ""))
print(f"Route walk: {total_refused}/{total_served} refused, {total_leaked} served")
print(f"Report written to {report_path}")
print("=" * 72)
if failed:
    for name, _s, detail in failed:
        print(f"  FAILED: {name}  :: {detail[:160]}")
