# Generated by Django 5.1.5 on 2026-09-08 12:05

import apps.employees.models
import core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=150)),
                ('relationship', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('employee_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('work_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
                ('photo', models.ImageField(blank=True, max_length=255, null=True, upload_to='employees/photos/')),
                ('pan', core.fields.EncryptedCharField(blank=True, plaintext_max_length=10)),
                ('aadhaar', core.fields.EncryptedCharField(blank=True, plaintext_max_length=12)),
                ('uan', models.CharField(blank=True, max_length=20)),
                ('esic_number', models.CharField(blank=True, max_length=20)),
                ('bank_account_number', core.fields.EncryptedCharField(blank=True, plaintext_max_length=20)),
                ('bank_ifsc', models.CharField(blank=True, max_length=11)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('intern', 'Intern'), ('consultant', 'Consultant')], default='full_time', max_length=20)),
                ('annual_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_of_joining', models.DateField()),
                ('probation_start_date', models.DateField(blank=True, null=True)),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('probation_status', models.CharField(choices=[('not_applicable', 'Not applicable'), ('active', 'In probation'), ('due', 'Review due'), ('confirmed', 'Confirmed'), ('extended', 'Extended'), ('terminated', 'Terminated in probation')], db_index=True, default='not_applicable', max_length=20)),
                ('date_of_exit', models.DateField(blank=True, null=True)),
                ('notice_period_days', models.PositiveSmallIntegerField(default=30)),
                ('status', models.CharField(choices=[('onboarding', 'Onboarding'), ('on_probation', 'On probation'), ('active', 'Active'), ('confirmed', 'Confirmed'), ('on_leave', 'On long leave'), ('on_notice', 'On notice'), ('resigned', 'Resigned'), ('terminated', 'Terminated'), ('exited', 'Exited')], db_index=True, default='active', max_length=20)),
            ],
            options={
                'ordering': ['employee_code'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('kind', models.CharField(choices=[('current', 'Current'), ('permanent', 'Permanent')], max_length=20)),
                ('line1', models.CharField(max_length=200)),
                ('line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('pincode', models.CharField(max_length=6)),
                ('country', models.CharField(default='India', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('file', models.FileField(max_length=255, upload_to=apps.employees.models.employee_document_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('degree', models.CharField(max_length=150)),
                ('institution', models.CharField(max_length=200)),
                ('year_of_passing', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('company', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=150)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProbationReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('probation_end_date', models.DateField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('performance_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reliability_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('role_specific_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('recommendation', models.CharField(choices=[('pending', 'Awaiting HR decision'), ('confirm', 'Confirm'), ('extend', 'Extend'), ('terminate', 'Terminate')], default='pending', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('decision', models.CharField(choices=[('pending', 'Awaiting HR decision'), ('confirm', 'Confirm'), ('extend', 'Extend'), ('terminate', 'Terminate')], db_index=True, default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('extended_to', models.DateField(blank=True, null=True)),
                ('notified_30d', models.BooleanField(default=False)),
                ('notified_7d', models.BooleanField(default=False)),
                ('notified_overdue_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-probation_end_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('category', models.CharField(choices=[('identity', 'Identity'), ('address', 'Address'), ('education', 'Education'), ('experience', 'Experience'), ('employment', 'Employment'), ('compliance', 'Compliance'), ('joining', 'Joining'), ('company_letter', 'Company letter'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('requires_expiry', models.BooleanField(default=False, help_text='Passports and visas expire; degree certificates do not.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
