# Generated by Django 5.1.5 on 2026-08-12 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
        ('recruitment', '0004_interview_excl_interviewer_double_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_from_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hired_as', to='recruitment.candidate'),
        ),
    ]
