# Generated by Django 5.1.5 on 2026-09-09 06:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_initial'),
        ('organization', '0001_initial'),
        ('recruitment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='code',
            field=models.SlugField(max_length=60),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='documenttype',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_documenttype_org_code'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('organization', 'employee_code'), name='uniq_employee_org_code'),
        ),
    ]
