# Generated by Django 5.1.5 on 2026-08-13 06:46

import apps.employees.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_created_from_candidate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbationReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('probation_end_date', models.DateField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('performance_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reliability_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('role_specific_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('recommendation', models.CharField(choices=[('pending', 'Awaiting HR decision'), ('confirm', 'Confirm'), ('extend', 'Extend'), ('terminate', 'Terminate')], default='pending', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('decision', models.CharField(choices=[('pending', 'Awaiting HR decision'), ('confirm', 'Confirm'), ('extend', 'Extend'), ('terminate', 'Terminate')], db_index=True, default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('extended_to', models.DateField(blank=True, null=True)),
                ('notified_30d', models.BooleanField(default=False)),
                ('notified_7d', models.BooleanField(default=False)),
                ('notified_overdue_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-probation_end_date'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_status',
            field=models.CharField(choices=[('not_applicable', 'Not applicable'), ('active', 'In probation'), ('due', 'Review due'), ('confirmed', 'Confirmed'), ('extended', 'Extended'), ('terminated', 'Terminated in probation')], db_index=True, default='not_applicable', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('on_probation', 'On probation'), ('active', 'Active'), ('confirmed', 'Confirmed'), ('on_leave', 'On long leave'), ('on_notice', 'On notice'), ('resigned', 'Resigned'), ('terminated', 'Terminated'), ('exited', 'Exited')], db_index=True, default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('category', models.CharField(choices=[('identity', 'Identity'), ('address', 'Address'), ('education', 'Education'), ('experience', 'Experience'), ('employment', 'Employment'), ('compliance', 'Compliance'), ('joining', 'Joining'), ('company_letter', 'Company letter'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('requires_expiry', models.BooleanField(default=False, help_text='Passports and visas expire; degree certificates do not.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('file', models.FileField(upload_to=apps.employees.models.employee_document_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='employees.documenttype')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
