# Generated by Django 5.1.5 on 2026-09-11 10:41

import apps.employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_documenttype_code_alter_employee_employee_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.employees.models.employee_photo_path),
        ),
    ]
