# Generated by Django 5.1.5 on 2026-08-13 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_probationreview_employee_probation_start_date_and_more'),
        ('onboarding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='probationreview',
            name='confirmation_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='onboarding.employeeletter'),
        ),
        migrations.AddField(
            model_name='probationreview',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='probationreview',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='probationreview',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probation_reviews', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='probationreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='probationreview',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['employee', 'status'], name='employees_e_employe_a6c000_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['status', 'expires_on'], name='employees_e_status_baa4c3_idx'),
        ),
        migrations.AddIndex(
            model_name='probationreview',
            index=models.Index(fields=['decision', 'probation_end_date'], name='employees_p_decisio_541e43_idx'),
        ),
        migrations.AddIndex(
            model_name='probationreview',
            index=models.Index(fields=['employee', '-created_at'], name='employees_p_employe_6d5903_idx'),
        ),
        migrations.AddConstraint(
            model_name='probationreview',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision', 'extend'), _negated=True), ('extended_to__isnull', False), _connector='OR'), name='ck_probation_extend_requires_a_new_date'),
        ),
    ]
