# Generated by Django 5.1.5 on 2026-08-17 10:19

import apps.employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_probationreview_confirmation_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='employees/photos/'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(max_length=255, upload_to=apps.employees.models.employee_document_path),
        ),
    ]
