# Generated by Django 5.1.5 on 2026-08-17 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_photo_alter_employeedocument_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['status', '-uploaded_at'], name='employees_e_status_e34c46_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeedocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'rejected'), _negated=True), models.Q(('rejection_reason', ''), _negated=True), _connector='OR'), name='ck_document_rejection_has_reason'),
        ),
    ]
