# Generated by Django 5.1.5 on 2026-08-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employeedocument_rejected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='annual_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
