# Generated by Django 5.1.5 on 2026-08-14 05:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('kind', models.CharField(choices=[('interview_scheduled', 'Interview scheduled'), ('interview_rescheduled', 'Interview rescheduled'), ('interview_feedback_due', 'Interview feedback due'), ('department_decision_recorded', 'Department decision awaiting HR'), ('candidate_rejected', 'Candidate rejected'), ('candidate_selected', 'Candidate selected'), ('offer_sent', 'Offer sent'), ('offer_accepted', 'Offer accepted'), ('onboarding_task_assigned', 'Onboarding task assigned'), ('onboarding_overdue', 'Onboarding task overdue'), ('probation_review_due', 'Probation review due'), ('probation_decided', 'Probation decision recorded'), ('document_expiring', 'Document expiring'), ('resignation_submitted', 'Resignation submitted'), ('clearance_task_assigned', 'Exit clearance task assigned'), ('exit_approved', 'Exit approved'), ('payroll_processed', 'Payroll processed and awaiting review'), ('payroll_approved', 'Payroll approved'), ('payroll_reversed', 'Payroll reversed'), ('payslip_available', 'Payslip available'), ('statutory_verification_due', 'Statutory rates awaiting verification'), ('asset_allocated', 'Asset allocated'), ('asset_return_due', 'Asset return due'), ('email_account_ready', 'Company account ready'), ('role_changed', 'Your access changed'), ('admin_override', 'Administrative override recorded')], db_index=True, max_length=40)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('link_url', models.CharField(blank=True, max_length=400)),
                ('entity_type', models.CharField(blank=True, max_length=120)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('channel', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed by preference')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('kind', models.CharField(choices=[('interview_scheduled', 'Interview scheduled'), ('interview_rescheduled', 'Interview rescheduled'), ('interview_feedback_due', 'Interview feedback due'), ('department_decision_recorded', 'Department decision awaiting HR'), ('candidate_rejected', 'Candidate rejected'), ('candidate_selected', 'Candidate selected'), ('offer_sent', 'Offer sent'), ('offer_accepted', 'Offer accepted'), ('onboarding_task_assigned', 'Onboarding task assigned'), ('onboarding_overdue', 'Onboarding task overdue'), ('probation_review_due', 'Probation review due'), ('probation_decided', 'Probation decision recorded'), ('document_expiring', 'Document expiring'), ('resignation_submitted', 'Resignation submitted'), ('clearance_task_assigned', 'Exit clearance task assigned'), ('exit_approved', 'Exit approved'), ('payroll_processed', 'Payroll processed and awaiting review'), ('payroll_approved', 'Payroll approved'), ('payroll_reversed', 'Payroll reversed'), ('payslip_available', 'Payslip available'), ('statutory_verification_due', 'Statutory rates awaiting verification'), ('asset_allocated', 'Asset allocated'), ('asset_return_due', 'Asset return due'), ('email_account_ready', 'Company account ready'), ('role_changed', 'Your access changed'), ('admin_override', 'Administrative override recorded')], max_length=40)),
                ('in_app', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['notification', 'channel'], name='notificatio_notific_7707f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(fields=('user', 'kind'), name='uniq_preference_per_kind'),
        ),
    ]
