# Generated by Django 5.1.5 on 2026-08-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('interview_scheduled', 'Interview scheduled'), ('interview_slot_selected', 'Interview slot chosen'), ('interview_rescheduled', 'Interview rescheduled'), ('interview_feedback_due', 'Interview feedback due'), ('department_decision_recorded', 'Department decision awaiting HR'), ('candidate_rejected', 'Candidate rejected'), ('candidate_selected', 'Candidate selected'), ('offer_sent', 'Offer sent'), ('offer_accepted', 'Offer accepted'), ('onboarding_task_assigned', 'Onboarding task assigned'), ('onboarding_overdue', 'Onboarding task overdue'), ('probation_review_due', 'Probation review due'), ('probation_decided', 'Probation decision recorded'), ('document_expiring', 'Document expiring'), ('document_uploaded', 'Document awaiting verification'), ('document_rejected', 'Your document was rejected'), ('resignation_submitted', 'Resignation submitted'), ('clearance_task_assigned', 'Exit clearance task assigned'), ('exit_approved', 'Exit approved'), ('payroll_processed', 'Payroll processed and awaiting review'), ('payroll_approved', 'Payroll approved'), ('payroll_reversed', 'Payroll reversed'), ('payslip_available', 'Payslip available'), ('statutory_verification_due', 'Statutory rates awaiting verification'), ('asset_allocated', 'Asset allocated'), ('asset_return_due', 'Asset return due'), ('email_account_ready', 'Company account ready'), ('role_changed', 'Your access changed'), ('admin_override', 'Administrative override recorded')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='kind',
            field=models.CharField(choices=[('interview_scheduled', 'Interview scheduled'), ('interview_slot_selected', 'Interview slot chosen'), ('interview_rescheduled', 'Interview rescheduled'), ('interview_feedback_due', 'Interview feedback due'), ('department_decision_recorded', 'Department decision awaiting HR'), ('candidate_rejected', 'Candidate rejected'), ('candidate_selected', 'Candidate selected'), ('offer_sent', 'Offer sent'), ('offer_accepted', 'Offer accepted'), ('onboarding_task_assigned', 'Onboarding task assigned'), ('onboarding_overdue', 'Onboarding task overdue'), ('probation_review_due', 'Probation review due'), ('probation_decided', 'Probation decision recorded'), ('document_expiring', 'Document expiring'), ('document_uploaded', 'Document awaiting verification'), ('document_rejected', 'Your document was rejected'), ('resignation_submitted', 'Resignation submitted'), ('clearance_task_assigned', 'Exit clearance task assigned'), ('exit_approved', 'Exit approved'), ('payroll_processed', 'Payroll processed and awaiting review'), ('payroll_approved', 'Payroll approved'), ('payroll_reversed', 'Payroll reversed'), ('payslip_available', 'Payslip available'), ('statutory_verification_due', 'Statutory rates awaiting verification'), ('asset_allocated', 'Asset allocated'), ('asset_return_due', 'Asset return due'), ('email_account_ready', 'Company account ready'), ('role_changed', 'Your access changed'), ('admin_override', 'Administrative override recorded')], max_length=40),
        ),
    ]
