# Generated by Django 5.1.5 on 2026-09-08 12:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metric_key', models.CharField(db_index=True, max_length=80)),
                ('dimension', models.JSONField(blank=True, default=dict)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['metric_key', '-period_start'],
                'indexes': [models.Index(fields=['metric_key', '-period_start'], name='reporting_m_metric__d49471_idx')],
                'constraints': [models.UniqueConstraint(fields=('metric_key', 'dimension', 'period_start'), name='uniq_snapshot_per_metric_dimension_period')],
            },
        ),
    ]
