# Generated by Django 5.1.5 on 2026-09-09 06:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_designation_uniq_designation_title_department_and_more'),
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='metricsnapshot',
            name='uniq_snapshot_per_metric_dimension_period',
        ),
        migrations.AddConstraint(
            model_name='metricsnapshot',
            constraint=models.UniqueConstraint(fields=('organization', 'metric_key', 'dimension', 'period_start'), name='uniq_snapshot_per_metric_dimension_period'),
        ),
    ]
