# Generated by Django 5.1.5 on 2026-09-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_remove_metricsnapshot_uniq_snapshot_per_metric_dimension_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricsnapshot',
            name='label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
